"use client";
import { useEffect, useState } from "react";
export default function JobsPage() {
  const [form, setForm] = useState({ title: "", company: "", location: "", description: "" }); const [jobs, setJobs] = useState<{ id: string; title: string; company?: string }[]>([]); const [error, setError] = useState("");
  async function load() { const response = await fetch("/api/career/opportunities"); const body = await response.json(); setJobs(body.opportunities || []); }
  useEffect(() => { load(); }, []);
  async function submit(event: React.FormEvent) { event.preventDefault(); setError(""); const response = await fetch("/api/career/opportunities", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify(form) }); const body = await response.json(); if (!response.ok) { setError(body.error || "Could not analyze job."); return; } window.location.href = "/career/jobs/" + body.opportunity.id; }
  return <main className="careerShell"><header className="careerHeader"><div><p className="careerEyebrow">CareerOS</p><h1>Explore a role</h1><p className="careerMuted">Paste a job description to see where your confirmed experience connects, transfers, or remains unresolved.</p></div><a href="/career/capabilities">Capabilities</a></header><section className="careerProfilePanel"><form className="careerForm" onSubmit={submit}><label>Role title<input required value={form.title} onChange={(e) => setForm({ ...form, title: e.target.value })} /></label><label>Company<input value={form.company} onChange={(e) => setForm({ ...form, company: e.target.value })} /></label><label>Location<input value={form.location} onChange={(e) => setForm({ ...form, location: e.target.value })} /></label><label>Job description<textarea required maxLength={50000} value={form.description} onChange={(e) => setForm({ ...form, description: e.target.value })} /></label><button className="careerPrimaryButton">Analyze role</button>{error && <p className="careerError">{error}</p>}</form></section>{jobs.length > 0 && <section className="careerProfilePanel careerNav"><h2>Saved roles</h2>{jobs.map((job) => <p key={job.id}><a href={"/career/jobs/" + job.id}>{job.title}{job.company ? ", " + job.company : ""}</a></p>)}</section>}</main>;
}
