"use client";
import { useEffect, useState } from "react";
type Job = { id: string; title: string; company?: string | null; location?: string | null; sourceUrl?: string | null; decisionState: string; matchSummary?: { headline?: string } | null; matchStale?: boolean | null };
const decisionLabels: Record<string, string> = { CONSIDERING: "Considering", PURSUE: "Pursue", PASS: "Pass" };
export default function JobsPage() {
  const [form, setForm] = useState({ title: "", company: "", location: "", sourceUrl: "", description: "" }); const [jobs, setJobs] = useState<Job[]>([]); const [selected, setSelected] = useState<string[]>([]); const [error, setError] = useState("");
  async function load() { const response = await fetch("/api/career/opportunities"); const body = await response.json(); setJobs(body.opportunities || []); }
  useEffect(() => { load(); }, []);
  async function submit(event: React.FormEvent) { event.preventDefault(); setError(""); const response = await fetch("/api/career/opportunities", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify(form) }); const body = await response.json(); if (!response.ok) { setError(body.error || "Could not analyze job."); return; } window.location.href = "/career/jobs/" + body.opportunity.id; }
  const compareHref = `/career/jobs/compare?ids=${selected.join(",")}`;
  return <main className="careerShell"><header className="careerHeader"><div><p className="careerEyebrow">CareerOS</p><h1>Your saved jobs</h1><p className="careerMuted">Add a role, understand how your confirmed experience connects, and return to your decision later.</p></div><span><a href="/career/inbox">Opportunity inbox</a> · <a href="/career/capabilities">Capabilities</a></span></header><section className="careerProfilePanel"><h2>Add a job</h2><form className="careerForm" onSubmit={submit}><label>Role title<input required value={form.title} onChange={(e) => setForm({ ...form, title: e.target.value })} /></label><label>Company<input value={form.company} onChange={(e) => setForm({ ...form, company: e.target.value })} /></label><label>Location<input value={form.location} onChange={(e) => setForm({ ...form, location: e.target.value })} /></label><label>Source URL <span className="careerMuted">(optional)<input type="url" placeholder="https://..." value={form.sourceUrl} onChange={(e) => setForm({ ...form, sourceUrl: e.target.value })} /></span></label><label>Job description<textarea required maxLength={50000} value={form.description} onChange={(e) => setForm({ ...form, description: e.target.value })} /></label><button className="careerPrimaryButton">Analyze role</button>{error && <p className="careerError">{error}</p>}</form></section>{jobs.length > 0 && <section className="careerProfilePanel careerNav"><div className="careerCompareToolbar"><div><h2>Saved jobs</h2><p className="careerMuted">Select 2 to 4 jobs to compare their existing analyses.</p></div><a className="careerPrimaryButton" aria-disabled={selected.length < 2 || selected.length > 4} href={selected.length >= 2 && selected.length <= 4 ? compareHref : undefined}>Compare jobs ({selected.length})</a></div>{jobs.map((job) => <article className="careerCandidate" key={job.id}><label className="careerJobSelect"><input type="checkbox" checked={selected.includes(job.id)} disabled={!selected.includes(job.id) && selected.length >= 4} onChange={(event) => setSelected((current) => event.target.checked ? [...current, job.id] : current.filter((id) => id !== job.id))} /><span><h3><a href={"/career/jobs/" + job.id}>{job.title}</a></h3><p className="careerMuted">{[job.company, job.location].filter(Boolean).join(" · ") || "User-supplied role"} · {decisionLabels[job.decisionState] || "Considering"}</p><p>{job.matchStale ? "Your career information changed since this analysis." : job.matchSummary?.headline || "Analysis available"}</p>{job.sourceUrl && <a href={job.sourceUrl} target="_blank" rel="noreferrer">Open source link</a>}<br /><a href={"/career/jobs/" + job.id}>Reopen analysis</a></span></label></article>)}</section>}</main>;
}
