# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "83114672506075ba4866194fe0160cde"
name = "cart-agent"
application_url = "https://pay.abando.ai"
embedded = true
handle = "cart-agent-1"

[build]
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2025-07"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_checkouts,read_orders,read_script_tags,write_checkouts,write_script_tags"
optional_scopes = [ ]
use_legacy_install_flow = false

[auth]
redirect_urls = [
  "https://pay.abando.ai/auth/callback",
  "https://dev.abando.ai/auth/shopify/callback",
  "https://pay.abando.ai/api/auth/callback"
]

[pos]
embedded = false
