"use client";
import { useState } from "react";
type Item = { id: string; title: string; company?: string | null; location?: string | null; sourceType: string; sourceUrl?: string | null; status: string; duplicateStatus: string; normalizationStatus: string; opportunityId?: string | null };
const labels: Record<string, string> = { MANUAL_TEXT: "Pasted job", JOB_URL: "Source link", EMAIL_ALERT: "Job alert", USER_FORWARD: "Forwarded job", API_IMPORT: "API import", FEED_IMPORT: "Feed import", OTHER: "Other" };
const statusLabels: Record<string, string> = { READY_TO_ANALYZE: "Ready to analyze", NEEDS_REVIEW: "Needs review", DUPLICATE: "Duplicate", IMPORTED: "Imported", DISMISSED: "Dismissed" };
export default function OpportunityInboxClient({ initialItems }: { initialItems: Item[] }) {
  const [items, setItems] = useState(initialItems); const [form, setForm] = useState({ sourceType: "MANUAL_TEXT", title: "", company: "", location: "", sourceUrl: "", description: "" }); const [message, setMessage] = useState("");
  async function importItem(event: React.FormEvent) { event.preventDefault(); setMessage(""); const response = await fetch("/api/career/opportunity-inbox", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify(form) }); const body = await response.json(); if (!response.ok) { setMessage(body.error || "Could not add opportunity."); return; } setItems((current) => [body.item, ...current]); setMessage(body.duplicate === "DUPLICATE" ? "This opportunity is already in your inbox." : "Opportunity added to your inbox."); }
  async function action(item: Item, actionName: string) { const response = await fetch("/api/career/opportunity-inbox/" + item.id, { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ action: actionName }) }); const body = await response.json(); if (!response.ok) { setMessage(body.error || "Could not update this opportunity."); return; } if (body.opportunity?.id) window.location.href = "/career/jobs/" + body.opportunity.id; else setItems((current) => current.map((value) => value.id === item.id ? body.item : value)); }
  return <><section className="careerProfilePanel"><h2>Bring in an opportunity</h2><p className="careerMuted">Paste a job description, add a source link as reference, or paste a job-alert message. A link alone is kept for review and does not trigger fetching.</p><form className="careerForm" onSubmit={importItem}><label>Source<select value={form.sourceType} onChange={(event) => setForm({ ...form, sourceType: event.target.value })}>{Object.entries(labels).map(([value, label]) => <option key={value} value={value}>{label}</option>)}</select></label><label>Role title<input required={form.sourceType !== "JOB_URL"} value={form.title} onChange={(event) => setForm({ ...form, title: event.target.value })} /></label><label>Company<input value={form.company} onChange={(event) => setForm({ ...form, company: event.target.value })} /></label><label>Location<input value={form.location} onChange={(event) => setForm({ ...form, location: event.target.value })} /></label><label>Source URL <span className="careerMuted">(optional)<input type="url" placeholder="https://..." value={form.sourceUrl} onChange={(event) => setForm({ ...form, sourceUrl: event.target.value })} /></span></label><label>Job description or alert text<textarea required={form.sourceType !== "JOB_URL"} maxLength={50000} value={form.description} onChange={(event) => setForm({ ...form, description: event.target.value })} /></label><button className="careerPrimaryButton">Add to inbox</button>{message && <p className="careerDraftState" role="status">{message}</p>}</form></section>{items.length > 0 && <section className="careerProfilePanel"><h2>New opportunities</h2>{items.map((item) => <article className="careerCandidate" key={item.id}><h3>{item.title}</h3><p className="careerMuted">{[item.company, item.location].filter(Boolean).join(" · ") || "Company not provided"} · {labels[item.sourceType] || "Imported source"}</p><p>{statusLabels[item.status] || item.status}{item.duplicateStatus !== "NEW" ? " · " + item.duplicateStatus.toLowerCase().replace("_", " ") : ""}</p>{item.sourceUrl && <a href={item.sourceUrl} target="_blank" rel="noreferrer">Open source link</a>}<div className="careerInterviewActions">{item.status === "READY_TO_ANALYZE" && <button className="careerPrimaryButton" type="button" onClick={() => action(item, "analyze")}>Analyze</button>}{(item.status === "DUPLICATE" || item.duplicateStatus === "POSSIBLE_DUPLICATE") && <button className="careerSmallButton" type="button" onClick={() => action(item, "resolve")}>Review as new opportunity</button>}{item.status !== "IMPORTED" && item.status !== "DISMISSED" && <button className="careerSmallButton" type="button" onClick={() => action(item, "dismiss")}>Dismiss</button>}{item.opportunityId && <a className="careerSmallButton" href={"/career/jobs/" + item.opportunityId}>Open analysis</a>}</div></article>)}</section>}</>;
}
