name: ci
on:
  pull_request:
  push:
    branches: [main]

jobs:
  deps-check:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: abando-frontend
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'npm'
      - run: bash scripts/git/deps-guard.sh check
      - run: npm ci --dry-run

  build-and-test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: abando-frontend
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'npm'
      - run: npm ci
      - run: npm run -s test:e2e:ci
      - if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report
          path: |
            abando-frontend/playwright-report/**
            abando-frontend/test-results/**
          if-no-files-found: ignore
