name: Verify deps & lockfile
on:
  pull_request:
  push:
    branches: ["**"]

jobs:
  deps-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout (PR head or current ref)
        uses: actions/checkout@v4
      - name: Print workspace + ls
        run: |
          echo "pwd: $(pwd)"
          echo "github.workspace: $GITHUB_WORKSPACE"
          echo "HEAD: $(git rev-parse --short HEAD)"
          ls -la
          echo "---- scripts tree (max 3) ----"
          find . -maxdepth 3 -type f -path "*scripts/*" -print | sort
          echo "---- ls scripts/git ----"
          ls -la ./scripts/git || true
          echo "---- tracked? ----"
          git ls-files scripts/git/deps-guard.sh || echo "NOT TRACKED"
          echo "---- head ----"
          [ -f scripts/git/deps-guard.sh ] && head -n 5 scripts/git/deps-guard.sh || echo "MISSING"
        with:
          ref: ${{ github.event.pull_request.head.sha || github.ref }}

      - name: Show repo root & verify guard script
        run: |
          set -euo pipefail
          pwd; ls -la
          test -f scripts/git/deps-guard.sh || (echo "MISSING: scripts/git/deps-guard.sh"; exit 1)
          chmod +x scripts/git/deps-guard.sh

      - uses: actions/setup-node@v4
        with:
          node-version: "22"
          cache: "npm"

      - name: Dependency guard (static)
        run: bash scripts/git/deps-guard.sh check

      - name: Lockfile integrity (npm ci dry-run)
        run: npm ci --dry-run
