apiVersion: apps/v1
kind: Deployment
metadata:
  name: cart-agent-backend
  namespace: cart-agent
spec:
  replicas: 1
  selector:
    matchLabels: { app: cart-agent-backend }
  template:
    metadata:
      labels: { app: cart-agent-backend }
    spec:
      containers:
        - name: web
          image: cart-agent:dev
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3000
          env:
            - name: NODE_ENV
              value: "production"
          readinessProbe:
            httpGet: { path: /health, port: 3000 }
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet: { path: /health, port: 3000 }
            initialDelaySeconds: 15
            periodSeconds: 20
