"use client";
import { useEffect, useState } from "react";
import { capabilityReviewComplete, nextUnreviewedCapabilityIndex, unreviewedCapabilityCount } from "../../../lib/career/capabilityReview.mjs";
type SupportingEvidence = { statement: string; sourceType?: string | null; sourceExcerpt?: string | null; scopeStatement?: string | null };
type Capability = { id: string; label: string; authorityState: string; supportingEvidence: SupportingEvidence[]; question: { key: string; prompt: string; choices: string[] } | null; decision?: { answer: string } | null };
const labels: Record<string, string> = { DIRECT: "Yes, directly", TRANSFERABLE: "Related experience", PARTIAL: "Part of this", NOT_SUPPORTED: "No, this does not describe my experience", KEEP_UNRESOLVED: "I need more context" };
export default function CapabilitiesPage() {
  const [items, setItems] = useState<Capability[]>([]); const [index, setIndex] = useState(0); const [saveNotice, setSaveNotice] = useState<{ capabilityId: string; text: string } | null>(null);
  useEffect(() => { fetch("/api/career/capabilities", { cache: "no-store" }).then((r) => r.json()).then((body) => setItems(body.profile?.capabilities || [])); }, []);
  const current = items[index]; const complete = capabilityReviewComplete(items); const unreviewed = unreviewedCapabilityCount(items);
  async function answer(answer: string) {
    if (!current?.question) return;
    const response = await fetch("/api/career/capabilities", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ capabilityId: current.id, questionKey: current.question.key, answer }) });
    if (!response.ok) { setSaveNotice({ capabilityId: current.id, text: "We could not save this answer." }); return; }
    setItems((previous) => previous.map((item, itemIndex) => itemIndex === index ? { ...item, authorityState: answer === "DIRECT" ? "VERIFIED_DIRECT" : answer === "TRANSFERABLE" ? "VERIFIED_TRANSFERABLE" : answer === "PARTIAL" ? "PARTIALLY_SUPPORTED" : answer === "NOT_SUPPORTED" ? "NOT_SUPPORTED" : "KEEP_UNRESOLVED", decision: { answer } } : item)); setSaveNotice({ capabilityId: current.id, text: "Answer saved" }); window.setTimeout(() => setSaveNotice((notice) => notice?.capabilityId === current.id ? null : notice), 2500);
  }
  function moveTo(nextIndex: number) { setSaveNotice(null); setIndex(nextIndex); }
  function moveToNextUnreviewed() { const next = nextUnreviewedCapabilityIndex(items, index); if (next >= 0) moveTo(next); }
  return <main className="careerShell"><header className="careerHeader"><div><p className="careerEyebrow">CareerOS</p><h1>Review your capabilities</h1><p className="careerMuted">A few reusable questions help CareerOS describe your experience without turning every job into a new questionnaire.</p></div><nav><a href="/career">Career home</a> · <a href="/career/profile">Profile</a> · <a href="/career/onboarding">Career Story</a></nav></header><section className="careerProfilePanel">{!current ? <p className="careerMuted">Confirm some career facts first, then return here.</p> : complete ? <><p className="careerEyebrow">Capability review complete</p><h2>You’ve reviewed your current capability questions.</h2><p className="careerMuted">You can update these answers at any time. This does not mean your professional profile is permanently complete.</p><nav className="careerNav"><a className="careerPrimaryButton" href="/career/inbox">Go to Opportunity Inbox</a><a className="careerLinkButton" href="/career">Career home</a><a className="careerLinkButton" href="/career/profile">Career profile</a><a className="careerLinkButton" href="/career/onboarding">Career Story</a></nav></> : <><p className="careerMuted">Question {index + 1} of {items.length} · {unreviewed} remaining</p><h2>{current.label}</h2><section aria-label="Capability evidence"><h3>Why CareerOS is asking</h3>{current.supportingEvidence.length ? <ul>{current.supportingEvidence.map((evidence, evidenceIndex) => <li key={`${current.id}-${evidenceIndex}`}><p>{evidence.statement}</p>{evidence.sourceType ? <p className="careerMuted">Source: {evidence.sourceType}</p> : null}{evidence.scopeStatement ? <p className="careerMuted">Scope: {evidence.scopeStatement}</p> : null}{evidence.sourceExcerpt ? <p className="careerMuted">Source excerpt: {evidence.sourceExcerpt}</p> : null}</li>)}</ul> : <p className="careerMuted">CareerOS is asking because this capability is not yet established from confirmed evidence.</p>}</section><p className="careerMuted">{current.question?.prompt}</p><div className="careerChoiceGrid">{(current.question?.choices || []).map((choice) => <button className="careerSmallButton" key={choice} onClick={() => answer(choice)} aria-pressed={current.decision?.answer === choice}>{labels[choice] || choice}</button>)}</div>{saveNotice?.capabilityId === current.id ? <p className="careerSaved" role="status">{saveNotice.text}</p> : null}<nav className="careerNav"><button className="careerLinkButton" disabled={index === 0} onClick={() => moveTo(index - 1)}>Previous</button><button className="careerLinkButton" onClick={moveToNextUnreviewed}>Next unreviewed</button><a className="careerLinkButton" href="/career/inbox">Opportunity Inbox</a></nav></>}</section></main>;
}
