import { createHash } from "node:crypto";
import { existsSync, readFileSync } from "node:fs";
import path from "node:path";
import { capabilityFamily, isCapabilityBearing, normalizeRequirement } from "./careerOsV1_26LRequirementReuse.mjs";

const text = (value) => typeof value === "string" ? value.trim() : "";
const POSITIVE = new Set(["PROVEN", "DIRECT", "TRANSFERABLE", "PARTIAL"]);
const specialist = (requirement) => Boolean(requirement?.specialist === true) || /finance|accounting|tax|payroll|legal|av[_ -]?media|software[_ -]?engineering|software engineer|data[_ -]?science|data scientist|machine learning|specialist ai|security/i.test([requirement?.requirementCategory, requirement?.requirementLevel, requirement?.requirementText, requirement?.technologyOrSkill].filter(Boolean).join(" "));
function scopeClassification(requirement) { const value = normalizeRequirement(requirement); if (/portfolio|enterprise|global|company wide|organization wide/.test(value)) return "PORTFOLIO_ENTERPRISE"; if (/manage people|direct reports|people manager|lead a team|team leadership/.test(value)) return "TEAM_LEADERSHIP"; if (/program leadership|program owner|own the program|program accountability|cross functional program/.test(value)) return "PROGRAM_LEADERSHIP"; if (/own|ownership|accountable|accountability|drive/.test(value)) return "OWNERSHIP"; if (/contribute|contributor|support|assist|partner/.test(value)) return "INDIVIDUAL_OR_CONTRIBUTOR"; return "UNSPECIFIED"; }
function importance(requirement) { return text(requirement?.importanceClassification) || "UNKNOWN"; }
function groupKey(requirement) { return `${capabilityFamily(requirement)}|${specialist(requirement) ? "SPECIALIST" : "GENERAL"}|${importance(requirement)}`; }
function stableHash(value) { return createHash("sha256").update(JSON.stringify(value)).digest("hex"); }
function loadRound1RequirementIds() { const file = path.join(process.env.HOME || "", ".staffordos/private/professional/job-search/adjudication/requirement-mapping-decisions.ndjson"); if (!existsSync(file)) return new Set(); const latest = new Map(); for (const line of readFileSync(file, "utf8").split(/\r?\n/).filter(Boolean)) { const decision = JSON.parse(line); latest.set(decision.requirementId, decision); } return new Set(latest.keys()); }

export function reconstructExactTargetManifest({ requirements = [], mappings = [], round1RequirementIds = null, sources = new Map(), originalQueue = null, reviewSetId = "V1_26M_SECOND_BOUNDED_REQUIREMENT_REVIEW" } = {}) {
  const round1Ids = round1RequirementIds || loadRound1RequirementIds();
  const currentMapping = new Map(mappings.map((mapping) => [mapping.requirementId, mapping]));
  const activePositive = new Set(mappings.filter((mapping) => POSITIVE.has(mapping.classification)).map((mapping) => mapping.requirementId));
  const eligible = requirements.filter((requirement) => isCapabilityBearing(requirement) && !activePositive.has(requirement.id) && !round1Ids.has(requirement.id) && ["UNKNOWN", "MISSING"].includes(currentMapping.get(requirement.id)?.classification));
  const groups = new Map(); for (const requirement of eligible) { const key = groupKey(requirement); if (!groups.has(key)) groups.set(key, []); groups.get(key).push(requirement); }
  const selectedGroups = [...groups.entries()].sort((a, b) => b[1].length - a[1].length || a[0].localeCompare(b[0])).slice(0, 30);
  const questions = []; const excluded = []; let order = 0;
  for (const [key, group] of selectedGroups) {
    const partitions = new Map(); for (const requirement of group) { const scope = scopeClassification(requirement); if (!partitions.has(scope)) partitions.set(scope, []); partitions.get(scope).push(requirement); }
    for (const [scope, targets] of [...partitions.entries()].sort((a, b) => a[0].localeCompare(b[0]))) {
      order += 1; const [family, specialistClass, importanceClass] = key.split("|"); const questionId = `review_gap_${String(order).padStart(2, "0")}`; const targetRequirements = targets.map((requirement) => { const source = sources.get(requirement.sourceId) || sources.get(requirement.sourceRecordId) || {}; return { requirementId: requirement.id, opportunityId: requirement.jobOpportunityId, sourceRecordId: source.jobSourceRecordId || null, sourceId: requirement.sourceId || null, providerName: source.providerName || null, company: source.company || null, role: source.title || source.role || null, exactRequirementText: requirement.requirementText, requirementType: requirement.requirementLevel || requirement.requirementCategory || null, requirementClassification: requirement.requirementCategory || null, capabilityFamily: family, specialist: specialistClass === "SPECIALIST", scopeClassification: scope, importance: importanceClass, sourceLineageReference: requirement.sourceExcerptReference || null, sourceOrder: requirement.sourceLocation?.lineNumber ?? null, sourceAuthority: requirement.sourceAuthority || null }; });
      questions.push({ reviewSetId, questionId, questionOrder: order, questionText: `Which bounded ${family.toLowerCase().replaceAll("_", " ")} capability and scope does your existing authority support for these exact requirements?`, capabilityFamily: family, specialistClass, scopeClassification: scope, importance: importanceClass, compressionReason: "Targets share the deterministic capability family, specialist boundary, importance class, and structural scope classification.", selectionReason: "Selected by the original recurrence/family/importance ordering over the locked unresolved capability-bearing requirement universe; labels excluded.", targetRequirements });
    }
  }
  const selectedTargetIds = new Set(questions.flatMap((question) => question.targetRequirements.map((target) => target.requirementId)));
  for (const requirement of eligible) if (!selectedTargetIds.has(requirement.id)) excluded.push({ reason: "OUTSIDE_TOP_30_OR_SCOPE_PARTITION", specialist: specialist(requirement), capabilityFamily: capabilityFamily(requirement) });
  const targetIds = questions.flatMap((question) => question.targetRequirements.map((target) => target.requirementId));
  const duplicateTargetCount = targetIds.length - new Set(targetIds).size;
  const originalDistribution = originalQueue ? Object.fromEntries(originalQueue.questions.map((question) => [question.capabilityFamily, (originalQueue.questions.filter((item) => item.capabilityFamily === question.capabilityFamily).length)])) : {};
  return { reviewSetId, originalQuestionCount: originalQueue?.queueSize ?? null, reconstructedQuestionCount: questions.length, originalDistribution, reconstructedDistribution: Object.fromEntries([...new Set(questions.map((question) => question.capabilityFamily))].sort().map((family) => [family, questions.filter((question) => question.capabilityFamily === family).length])), eligibleRequirementCount: eligible.length, activePositiveMappingCount: activePositive.size, questions, excluded, duplicateTargetCount, uniqueTargetRequirements: new Set(targetIds).size, specialistTargetCount: targetIds.filter((id) => questions.flatMap((question) => question.targetRequirements).find((target) => target.requirementId === id)?.specialist).length, scopeSensitiveTargetCount: targetIds.filter((id) => { const target = questions.flatMap((question) => question.targetRequirements).find((item) => item.requirementId === id); return target && target.scopeClassification !== "UNSPECIFIED"; }).length, round1OverlapCount: targetIds.filter((id) => activePositive.has(id)).length, manifestHash: stableHash(questions), noLabelsUsed: true };
}
