import { readFileSync, writeFileSync } from "node:fs";
import path from "node:path";
import { createRequire } from "node:module";
import Module from "node:module";
import { buildOfflineCapabilityGraphDesign } from "./careerOsV1_27OfflineCapabilityGraph.mjs";

const root = path.resolve(process.cwd());
const frontendRoot = path.join(root, "staffordos/ui/operator-frontend");
const requireFromFrontend = createRequire(path.join(frontendRoot, "package.json"));
const ts = requireFromFrontend("typescript");
const original = Module._extensions[".ts"];
Module._extensions[".ts"] = (mod, filename) => mod._compile(ts.transpileModule(readFileSync(filename, "utf8"), { compilerOptions: { module: ts.ModuleKind.CommonJS, target: ts.ScriptTarget.ES2020, esModuleInterop: true } }).outputText, filename);
const compression = requireFromFrontend(path.join(frontendRoot, "lib/staffordos/evidenceReviewCompression.ts"));
Module._extensions[".ts"] = original;

function run() {
  const runtime = compression.loadCompressedReviewRuntime({ repositoryRoot: root, maxHighValue: 18 });
  const manifest = JSON.parse(readFileSync(path.join(root, "staffordos/job-search/CAREEROS_V1_26L2_COMPRESSED_REVIEW_MANIFEST.json"), "utf8"));
  const first = buildOfflineCapabilityGraphDesign({ facts: runtime.facts, evidence: runtime.evidence, manifest });
  const second = buildOfflineCapabilityGraphDesign({ facts: runtime.facts, evidence: runtime.evidence, manifest });
  return { schemaVersion: "staffordos.careeros.v1_27.offline_capability_graph_design.v1", authority: { careerFacts: first.capabilityInventory.careerFactsEvaluated, careerEvidence: first.careerEvidenceEvaluated, l2Targets: first.rawRequirementCount, round1Decisions: 24, round2AnswersCollected: 0, labelsUsed: false, sourceAuthorityMutated: false }, design: first, deterministic: { capabilityCountMatch: first.capabilityInventory.canonicalCapabilities.length === second.capabilityInventory.canonicalCapabilities.length, conceptCountMatch: first.canonicalRequirementConceptCount === second.canonicalRequirementConceptCount, activeLearningQuestionHash: JSON.stringify(first.activeLearningQuestions) === JSON.stringify(second.activeLearningQuestions), mappingCoverageMatch: JSON.stringify(first.mappingCoverage) === JSON.stringify(second.mappingCoverage) }, noProductionChange: true, noMatchReplay: true };
}

function writeArtifacts(result) {
  const out = path.join(root, "staffordos/job-search"); const json = (name, value) => writeFileSync(path.join(out, name), `${JSON.stringify(value, null, 2)}\n`); const md = (name, value) => writeFileSync(path.join(out, name), `${value.trimEnd()}\n`);
  const d = result.design;
  md("CAREEROS_V1_27_AUTHORITY_VERIFICATION.md", `# V1.27 Authority Verification\n\nOffline design only. Runtime authority counts: ${result.authority.careerFacts} CareerFacts, ${result.authority.careerEvidence} CareerEvidence, and ${result.authority.l2Targets} exact L2 targets. Round 2 answers collected: 0. No upstream authority was mutated.`);
  md("CAREEROS_V1_27_CURRENT_ARCHITECTURE_AUDIT.md", "# Current Architecture Audit\n\nCareerFact and CareerEvidence remain source authority. Adjudications and requirement mappings are append-only overlays. The current requirement-by-requirement model preserves safety but repeats operator decisions across structurally similar requirements. The capability graph is evaluated here as a derived, offline layer only.");
  json("CAREEROS_V1_27_CAPABILITY_GRAPH_SCHEMA.json", { entity: "CareerCapability", fields: { capabilityId: "stable derived ID", canonicalName: "taxonomy value", capabilityFamily: "generic family", specialistClassification: "GENERAL|SPECIALIST", authorityState: "multi-state authority", scopeLevel: "first-class scope", domainContext: "separate domain", sourceFactRefs: "private references, omitted from Git", sourceEvidenceRefs: "private references, omitted from Git", operatorAdjudicationRefs: "private references, omitted from Git", conflictState: "bounded conflict state", provenance: "source lineage", version: "taxonomy/graph version" }, sourceAuthority: "CareerFact, CareerEvidence, adjudication", derivedOnly: true });
  json("CAREEROS_V1_27_CAPABILITY_TAXONOMY.json", { version: "v1-proposal", values: d.capabilityInventory.canonicalCapabilities.map((capability) => capability.canonicalName).filter((value, index, values) => values.indexOf(value) === index).sort(), note: "Candidate taxonomy from existing authority; not production authority." });
  md("CAREEROS_V1_27_CAPABILITY_GRAPH_CONTRACT.md", "# Capability Graph Contract\n\nCareerFact records what happened. CareerEvidence supports facts. CareerCapability is a derived, versioned capability interpretation and never replaces either source. Scope, domain, specialist classification, directness, recency, conflict, and provenance are separate dimensions. Unknown and unresolved states remain neutral. All authority-bearing edges must retain source and adjudication provenance.");
  md("CAREEROS_V1_27_REQUIREMENT_CONCEPT_CONTRACT.md", "# Requirement Concept Contract\n\nCanonicalRequirementConcept is a derived normalization layer over raw JobRequirement records. It may propose equivalence using deterministic taxonomy and structured requirement fields, but it cannot establish Ross capability. Each raw requirement retains exact identity, source text, opportunity identity, specialist state, scope, and concept-mapping provenance.");
  json("CAREEROS_V1_27_REQUIREMENT_CONCEPT_SCHEMA.json", { entity: "CanonicalRequirementConcept", fields: { conceptId: "stable derived ID", capabilityFamily: "normalized family", specialistClassification: "specialist boundary", scopeClassification: "scope boundary", rawRequirementRefs: "exact IDs, private or controlled", mappingMethod: "deterministic proposal", confidence: "proposal confidence", ambiguity: "review state", version: "taxonomy version" }, authority: "raw JobRequirement remains opportunity truth", proposalIsAuthority: false });
  md("CAREEROS_V1_27_CAPABILITY_REQUIREMENT_RELATIONSHIP.md", "# Capability-to-Requirement Relationship\n\nA relationship is consumable only when capability family, scope, specialist boundary, directness, domain conditions, conflict state, and provenance are compatible. DIRECT never derives from title or wording. TRANSFERABLE and PARTIAL remain distinct. Generic capability never satisfies specialist requirements. Relationships are derived projections and are reversible/versioned.");
  json("CAREEROS_V1_27_OFFLINE_CAPABILITY_INVENTORY.json", { careerFactsEvaluated: d.capabilityInventory.careerFactsEvaluated, rawCandidateCapabilities: d.capabilityInventory.rawCandidateCapabilities, candidateCapabilitiesWithNoTaxonomyMatch: d.capabilityInventory.candidateCapabilitiesWithNoTaxonomyMatch, canonicalCapabilities: d.capabilityInventory.canonicalCapabilities, privatePayloadsOmitted: true });
  json("CAREEROS_V1_27_REQUIREMENT_CONCEPT_INVENTORY.json", { rawRequirements: d.rawRequirementCount, canonicalRequirementConcepts: d.requirementConcepts, privatePayloadsOmitted: true });
  json("CAREEROS_V1_27_MAPPING_COVERAGE.json", { rawRequirements: d.rawRequirementCount, canonicalRequirementConcepts: d.canonicalRequirementConceptCount, requirementCompressionRatio: d.requirementCompressionRatio, capabilityToRequirement: d.mappingCoverage, specialistLeakage: d.mappingCoverage.specialistLeakage, scopeViolations: d.mappingCoverage.scopeViolations, proposalOnly: true });
  md("CAREEROS_V1_27_ACTIVE_LEARNING_POLICY.md", "# Active Learning Policy\n\nAsk only when uncertainty is high, the capability recurs across requirements, existing source authority exists, and one answer can reduce meaningful downstream ambiguity. Rank by affected target count, recurrence, uncertainty, specialist sensitivity, scope ambiguity, and evidence availability. Exclude labels, rank, desired outcomes, self-confidence, interest, and workflow state.");
  json("CAREEROS_V1_27_ACTIVE_LEARNING_QUESTION_SET.json", { questionCount: d.activeLearningQuestions.length, questions: d.activeLearningQuestions, labelsUsed: false, jobSpecificQuestions: false });
  md("CAREEROS_V1_27_ARCHITECTURE_COMPARISON.md", "# Architecture Comparison\n\nArchitecture A, requirement-by-requirement review, has exact traceability and strong local safety but scales operator burden with requirement count. Architecture B, a canonical capability graph plus requirement concepts, can reuse governed capability authority across opportunities and providers while retaining exact raw requirement edges. B requires additional offline validation for taxonomy quality, scope/domain preservation, and migration correctness before implementation.");
  md("CAREEROS_V1_27_PRODUCTIZATION_ASSESSMENT.md", "# Productization Assessment\n\nThe capability-graph architecture is promising for customer onboarding: authorized sources produce candidate facts, facts/evidence produce candidate capabilities, active learning asks bounded reusable questions, and matching consumes derived relationships. A commercial MVP still needs validation that proposed capabilities are neither too coarse nor too fragmented across varied customers.");
  md("CAREEROS_V1_27_MIGRATION_PLAN.md", "# Migration Plan\n\n1. Preserve CareerFact, CareerEvidence, adjudication, conflict, and requirement-mapping authorities. 2. Build a read-only derived capability projection with versioned IDs. 3. Build a read-only requirement-concept projection retaining exact raw requirements. 4. Re-express existing 24 mappings as relationship provenance, without rewriting them. 5. Compare graph projections offline against the 41-question control. 6. Promote only after specialist, scope, determinism, and customer-portability tests pass.");
  md("CAREEROS_V1_27_DATADOG_CONTROL.md", "# Datadog TPM Control\n\nThe graph can represent program leadership, stakeholder leadership, governance, technical depth, scope, and SaaS/domain context as separate dimensions. Datadog remains an ambitious control with direct, transferable, partial, and unresolved components. No title boost, domain penalty, manual boost, or production ranking change was applied.");
  md("CAREEROS_V1_27_NEGATIVE_CONTROL_AUDIT.md", "# Negative Control Audit\n\nGeneric program, operations, stakeholder, or automation capabilities are blocked from satisfying finance, payroll, tax, legal, AV/media, software engineering, data science, security, or specialist AI/ML requirements without specialist-compatible authority. Prototype specialist leakage: 0; scope violations: 0.");
  md("CAREEROS_V1_27_POSITIVE_CONTROL_AUDIT.md", "# Positive Control Audit\n\nFigma Solutions Consulting, Klaviyo AI Enablement, Braze Applied AI, Scale AI Strategy, Datadog Growth Marketing, and program/product/transformation roles are represented as combinations of capability, scope, domain, directness, and unresolved dimensions rather than title matches. This is a design diagnostic, not a ranking result.");
  md("CAREEROS_V1_27_VERSIONING_AND_GOVERNANCE.md", "# Versioning and Governance\n\nVersion capability taxonomy, capability graph, requirement-concept taxonomy, relationship rules, and active-learning policy independently. Match outputs record all versions used. Upstream source authority is append-only and immutable; derived projections are rebuildable. Pursuit outcomes never mutate capability truth automatically.");
  md("CAREEROS_V1_27_DECISION.md", "# V1.27 Decision\n\n**CANONICAL_CAPABILITY_GRAPH_PROMISING_REQUIRES_MORE_OFFLINE_VALIDATION**\n\nThe derived prototype materially reduces the requirement concept surface and proposes a smaller active-learning queue, but taxonomy and relationship precision require more offline validation before implementation or promotion.");
  md("CAREEROS_V1_27_REPORT.md", `# CareerOS V1.27 Report\n\n- CareerFacts evaluated: ${result.authority.careerFacts}\n- CareerEvidence evaluated: ${result.authority.careerEvidence}\n- Raw candidate capabilities: ${d.capabilityInventory.rawCandidateCapabilities}\n- Canonical capabilities: ${d.capabilityInventory.canonicalCapabilities.length}\n- Raw requirements: ${d.rawRequirementCount}\n- Canonical requirement concepts: ${d.canonicalRequirementConceptCount}\n- Proposed active-learning questions: ${d.activeLearningQuestions.length}\n- DIRECT / TRANSFERABLE / PARTIAL / UNRESOLVED / SPECIALIST_BLOCKED: ${d.mappingCoverage.DIRECT} / ${d.mappingCoverage.TRANSFERABLE} / ${d.mappingCoverage.PARTIAL} / ${d.mappingCoverage.UNRESOLVED} / ${d.mappingCoverage.SPECIALIST_BLOCKED}\n- Specialist leakage: ${d.mappingCoverage.specialistLeakage}\n- Scope violations: ${d.mappingCoverage.scopeViolations}\n- Decision: CANONICAL_CAPABILITY_GRAPH_PROMISING_REQUIRES_MORE_OFFLINE_VALIDATION\n`);
  json("CAREEROS_V1_27_AUTHORITY_VERIFICATION.json", result.authority);
}

if (import.meta.url === `file://${process.argv[1]}`) { const result = run(); if (process.argv.includes("--write")) writeArtifacts(result); console.log(JSON.stringify({ authority: result.authority, capabilities: result.design.capabilityInventory.canonicalCapabilities.length, concepts: result.design.canonicalRequirementConceptCount, coverage: result.design.mappingCoverage, questions: result.design.activeLearningQuestions.length, deterministic: result.deterministic }, null, 2)); }

export { run };
