import { redirect } from "next/navigation";
import { currentCareerContext } from "../../../../../lib/career/careerP0Auth";
import { getApplicationEvidencePacket } from "../../../../../lib/career/careerP0Product.mjs";

const groups = [["direct", "Strong direct evidence"], ["transferable", "Transferable experience"], ["partial", "Partial evidence"], ["unknown", "More evidence needed"], ["specialist", "Specialist constraints"], ["scope", "Scope constraints"]] as const;
export const runtime = "nodejs";

export default async function ApplicationEvidencePage({ params }: { params: Promise<{ opportunityId: string }> }) {
  const context = await currentCareerContext(); if (!context) redirect("/career/login");
  const opportunityId = (await params).opportunityId;
  const packet: any = await getApplicationEvidencePacket(context, opportunityId);
  return <main className="careerShell"><header className="careerHeader"><div><p className="careerEyebrow">Application evidence</p><h1>{packet.opportunity?.title || "Application evidence"}</h1><p className="careerMuted">{packet.opportunity?.company || "User-supplied role"}{packet.opportunity?.location ? " · " + packet.opportunity.location : ""}</p></div><a href={`/career/jobs/${opportunityId}`}>Back to job</a></header>{packet.status === "APPLICATION_EVIDENCE_STALE" && <section className="careerWarning"><strong>Application evidence is out of date.</strong><p>{packet.message}</p><a href={`/career/jobs/${opportunityId}`}>Re-analyze this job</a></section>}{packet.status === "APPLICATION_EVIDENCE_UNAVAILABLE" && <section className="careerProfilePanel"><h2>Analyze this job first</h2><p>{packet.message}</p></section>}{packet.status === "CURRENT" && <><section className="careerProfilePanel"><h2>Truthful evidence packet</h2><p className="careerMuted">This organizes confirmed experience for future application materials. It does not write final materials or predict hiring.</p></section>{groups.map(([key, label]) => <section className="careerProfilePanel" key={key}><h2>{label}</h2>{packet.sections[key].length === 0 ? <p className="careerMuted">None identified.</p> : packet.sections[key].map((item: any, index: number) => <article className="careerEvidenceItem" key={`${key}-${index}`}><h3>{item.requirement}</h3><p>{item.explanation}</p>{item.capability && <p><strong>Relevant experience:</strong> {item.capability}</p>}{item.evidence.length > 0 && <details><summary>How CareerOS knows this</summary>{item.evidence.map((evidence: any, evidenceIndex: number) => <div className="careerEvidence" key={evidenceIndex}><p>{evidence.statement}</p>{evidence.sourceType && <p className="careerMuted">Source: {evidence.sourceType}</p>}{evidence.scopeStatement && <p className="careerMuted">Scope: {evidence.scopeStatement}</p>}{evidence.sourceExcerpt && <p className="careerMuted">Source excerpt: {evidence.sourceExcerpt}</p>}</div>)}</details>}</article>)}</section>)}</>}</main>;
}
