/**
 * Playground routes:
 *   GET /demo            -> simple landing explaining the demo
 *   GET /demo/playground -> HTML shell (includes <script src="/demo/playground.js">)
 *   GET /demo/playground.js -> client JS (assembled without backticks)
 */
export function installPlayground(app){
  console.log(["playground"], "mounting /demo, /demo/playground, /demo/playground.js");
  function page({ title, body, head="" }) {
    return [
      '<!doctype html><html lang="en"><head>',
      '<meta charset="utf-8"/>',
      '<meta name="viewport" content="width=device-width,initial-scale=1"/>',
      '<title>' + title + '</title>',
      '<style>',
      ':root{color-scheme:dark}',
      '*{box-sizing:border-box}',
      'body{margin:0;background:#0b0b0c;color:#f2f2f2;font-family:system-ui,-apple-system,Segoe UI,Roboto,sans-serif}',
      '.wrap{max-width:980px;margin:0 auto;padding:40px 20px}',
      '.card{background:#121214;border:1px solid #222;border-radius:16px;padding:22px}',
      'h1{font-size:clamp(28px,5vw,42px);margin:.2rem 0 1rem}',
      '.lead{opacity:.9;font-size:clamp(16px,2.2vw,19px);line-height:1.7}',
      '.row{display:flex;flex-wrap:wrap;gap:12px;margin:14px 0}',
      '.kv{flex:1 1 240px;background:#0f0f11;border:1px solid #222;border-radius:12px;padding:12px}',
      '.kv b{display:block;opacity:.75;font-weight:600;margin-bottom:4px}',
      '.cta{display:inline-block;padding:12px 16px;border-radius:12px;background:#5b8cff;color:#0b0b0c;font-weight:800;text-decoration:none}',
      '.ghost{display:inline-block;padding:12px 16px;border-radius:12px;background:#0f0f11;border:1px solid #222;color:#f2f2f2;text-decoration:none}',
      '.small{opacity:.65;font-size:12px;margin-top:10px}',
      'input,select,button,textarea{font:inherit}',
      'input[type=text],input[type=number],select,textarea{width:100%;padding:10px;border-radius:10px;border:1px solid #333;background:#0e0e10;color:#f2f2f2}',
      'textarea{min-height:120px;white-space:pre-wrap}',
      '</style>',
      head,
      '</head><body><div class="wrap">',
      body,
      '</div></body></html>'
    ].join('');
  }

  app.get('/demo', (_req, res) => {
    const body = [
      '<div class="card">',
      '<h1>Abando Demo</h1>',
      '<p class="lead">Try the recovery copilot before you buy. Tweak the tone, channel, CTA, and see projected lift with your numbers.</p>',
      '<p><a class="cta" href="/demo/playground">Open the Playground</a>',
      ' <a class="ghost" href="/pricing" style="margin-left:8px">View pricing</a></p>',
      '</div>',
      '<footer class="small" style="opacity:.6;margin-top:18px">© <span id="y"></span> Abando™</footer>',
      '<script>document.getElementById("y").textContent=(new Date()).getFullYear()</script>'
    ].join('');
    res.status(200).type('html').send(page({ title: 'Abando – Demo', body }));
  });

  app.get('/demo/playground', (_req, res) => {
    const body = [
      '<div class="card">',
      '<h1>Interactive Playground</h1>',
      '<p class="lead">Configure the message you\'d send to recover carts. Then copy the result or share a link to this setup.</p>',
      '<div id="pg"></div>',
      '<p style="margin-top:12px">',
      '<a class="ghost" href="/pricing">Back to pricing</a>',
      '</p>',
      '</div>',
      '<footer class="small" style="opacity:.6;margin-top:18px">© <span id="y"></span> Abando™</footer>',
      '<script>document.getElementById("y").textContent=(new Date()).getFullYear()</script>',
      '<script src="/demo/playground.js" defer></script>'
    ].join('');
    res.status(200).type('html').send(page({ title: 'Abando – Playground', body }));
  });

  // Serve the client JS assembled from strings (no backticks anywhere)
  app.get('/demo/playground.js', (_req, res) => {
    const lines = [];

    // Minimal DOM builder & UI
    lines.push('(function(){',
      '  var el = document.getElementById("pg");',
      '  if(!el){ return; }',
      '  function h(tag, attrs, html){',
      '    var s = "<" + tag; attrs = attrs||{};',
      '    for(var k in attrs){ if(attrs.hasOwnProperty(k) && attrs[k]!==null){ s += " " + k + "=\\"" + String(attrs[k]).replace(/"/g, "&quot;") + "\\""; } }',
      '    s += ">"; if(html){ s += html; } s += "</" + tag + ">"; return s;',
      '  }',
      '  var controls = [',
      '    h("div",{class:"row"},',
      '      h("div",{class:"kv",style:"flex:2 1 320px"},',
      '        h("b",null,"Audience & Offer") +',
      '        h("div",null,',
      '          "<label>First name</label>"+h("input",{type:"text",id:"firstName",placeholder:"Alex"}) +',
      '          "<label style=\\"display:block;margin-top:8px\\">Product name</label>"+h("input",{type:"text",id:"productName",placeholder:"Canvas Tote"}) +',
      '          "<label style=\\"display:block;margin-top:8px\\">Checkout URL</label>"+h("input",{type:"text",id:"checkoutUrl",placeholder:"https://yourstore.com/checkout"}) +',
      '          "<label style=\\"display:block;margin-top:8px\\">Offer</label>"+',
      '          h("select",{id:"offer"},',
      '            "<option>None</option><option>Free shipping</option><option>10% off</option><option>$10 off</option>"',
      '          ) +',
      '          "<label style=\\"display:block;margin-top:8px\\">Timing</label>"+',
      '          h("select",{id:"timing"},',
      '            "<option>24 hours</option><option>3 days</option><option>7 days</option>"',
      '          )',
      '        )',
      '      ) +',
      '      h("div",{class:"kv",style:"flex:1 1 240px"},',
      '        h("b",null,"Style & Channel") +',
      '        h("div",null,',
      '          "<label>Tone</label>"+h("select",{id:"tone"}, "<option>Friendly</option><option>Direct</option><option>Playful</option><option>Urgent</option><option>Minimal</option>") +',
      '          "<label style=\\"display:block;margin-top:8px\\">Channel</label>"+h("select",{id:"channel"}, "<option>Email</option><option>SMS</option><option>On-site nudge</option>") +',
      '          "<label style=\\"display:block;margin-top:8px\\">Length</label>"+h("select",{id:"length"}, "<option>Short</option><option>Medium</option><option>Long</option>") +',
      '          "<label style=\\"display:block;margin-top:8px\\">CTA label</label>"+h("input",{type:"text",id:"ctaLabel",placeholder:"Resume checkout"})',
      '        )',
      '      )',
      '    ),',
      '    h("div",{class:"row"},',
      '      h("div",{class:"kv",style:"flex:2 1 420px"},',
      '        h("b",null,"Tokens") +',
      '        h("label",null, h("input",{type:"checkbox",id:"tokName",checked:"checked"}) + " Include first name") +',
      '        "<br/>"+ h("label",null, h("input",{type:"checkbox",id:"tokProd",checked:"checked"}) + " Include product") +',
      '        "<br/>"+ h("label",null, h("input",{type:"checkbox",id:"tokUrl",checked:"checked"}) + " Include checkout URL") +',
      '        "<br/>"+ h("label",null, h("input",{type:"checkbox",id:"tokDisc"}) + " Include discount code token")',
      '      ) +',
      '      h("div",{class:"kv",style:"flex:1 1 240px"},',
      '        h("b",null,"Revenue Estimator") +',
      '        "<label>AOV ($)</label>"+h("input",{type:"number",id:"aov",value:"80",min:"0"}) +',
      '        "<label style=\\"display:block;margin-top:8px\\">Monthly sessions</label>"+h("input",{type:"number",id:"sessions",value:"10000",min:"0"}) +',
      '        "<label style=\\"display:block;margin-top:8px\\">Abandon rate %</label>"+h("input",{type:"number",id:"aband",value:"70",min:"0",max:"100"}) +',
      '        "<label style=\\"display:block;margin-top:8px\\">Recovery rate %</label>"+h("input",{type:"number",id:"recovery",value:"2",min:"0",max:"100"}) +',
      '        "<button id=\\"calcBtn\\" class=\\"ghost\\" style=\\"margin-top:8px\\">Recalculate</button>"+',
      '        "<div id=\\"calcOut\\" class=\\"small\\" style=\\"margin-top:6px\\"></div>"',
      '      )',
      '    ),',
      '    h("div",{class:"row"},',
      '      h("div",{class:"kv",style:"flex:1 1 100%"},',
      '        h("b",null,"Preview A") + h("textarea",{id:"preview"})',
      '      ) +',
      '      h("div",{class:"kv",style:"flex:1 1 100%"},',
      '        h("b",null,"Preview B") + h("textarea",{id:"previewB"})',
      '      )',
      '    ),',
      '    "<div style=\\"margin-top:8px\\">"+',
      '      h("button",{id:"genBtn",class:"cta"},"Generate copy") +',
      '      " "+ h("button",{id:"shareBtn",class:"ghost"},"Share settings") +',
      '    "</div>"',
      '  ].join("");',
      '  el.innerHTML = controls;',
      '',
      '  function toneWrap(text, tone){',
      '    var tweaks = {',
      '      "Friendly":[["We noticed","Hey! We noticed"],["Please","Mind taking a look?"],["Reminder:","Quick reminder:"]],',
      '      "Direct":[["We noticed","You left"],["Please",""],["Reminder:",""]],',
      '      "Playful":[["Hi","Hey"],["We noticed","Psst—"],["Reminder:","Heads up:"]],',
      '      "Urgent":[["We noticed","Last chance:"],["We’ll hold your cart","Your cart expires soon!"]],',
      '      "Minimal":[["Hi",""],["We noticed","Reminder:"],["Please",""]]',
      '    }[tone]||[];',
      '    var out=text; for(var i=0;i<tweaks.length;i++){ out = out.split(tweaks[i][0]).join(tweaks[i][1]); }',
      '    return out;',
      '  }',
      '  function byChannel(base, ch, cta){',
      '    if(ch==="SMS"){',
      '      var s = base.replace(/\\n+/g," ").slice(0,240);',
      '      return s + (cta ? " Reply STOP to opt out. \\n" + cta : "");',
      '    }',
      '    if(ch==="On-site nudge"){',
      '      var one = base.split("\\n").slice(0,2).join(" ");',
      '      return one + (cta ? "\\n[ " + cta + " ]" : "");',
      '    }',
      '    return base + (cta ? "\\n\\n→ " + cta : "");',
      '  }',
      '  function offerLine(offer){',
      '    if(offer==="None") return "";',
      '    if(offer==="Free shipping") return "We\\u2019ll cover shipping\\u2014no code needed.";',
      '    if(offer==="10% off") return "Use code SAVE10 at checkout.";',
      '    if(offer==="$10 off") return "Use code TAKE10 at checkout.";',
      '    return "";',
      '  }',
      '  function timingLine(timing){ return "We\\u2019ll hold your cart for " + timing + "."; }',
      '  function tokens(s, cfg){',
      '    function rep(a,b){ return s.split(a).join(b); }',
      '    s = rep("{{first_name}}", cfg.firstName || "there");',
      '    s = rep("{{product_name}}", cfg.productName || "your items");',
      '    s = rep("{{checkout_url}}", cfg.checkoutUrl || "your checkout");',
      '    s = rep("{{discount_code}}", (cfg.offer==="10% off")?"SAVE10":(cfg.offer==="$10 off")?"TAKE10":"");',
      '    return s;',
      '  }',
      '  function baseCopy(cfg){',
      '    var greet = cfg.includeName ? "Hi {{first_name}}," : "Hi,";',
      '    var prod = cfg.includeProd ? " your {{product_name}}" : " your cart";',
      '    var body = greet + "\\n" +',
      '      "We noticed you left" + prod + ". " + offerLine(cfg.offer) + "\\n" +',
      '      timingLine(cfg.timing) + "\\n" +',
      '      (cfg.includeUrl ? "Pick up where you left off: {{checkout_url}}" : "");',
      '    return tokens(toneWrap(body, cfg.tone), cfg);',
      '  }',
      '  function altVariant(text){',
      '    return text.replace(/We noticed/g,"Just a nudge:")',
      '               .replace(/Pick up where you left off/g,"Jump back in")',
      '               .replace(/We\\u2019ll hold your cart/g,"We\\u2019re saving your picks");',
      '  }',
      '  function localize(s, lang){',
      '    if(lang==="es"){',
      '      return s.replace(/Hi/g,"Hola")',
      '              .replace(/We noticed/g,"Vimos")',
      '              .replace(/Pick up where you left off/g,"Contin\\u00FAa tu compra")',
      '              .replace(/We\\u2019ll hold your cart/g,"Guardaremos tu carrito");',
      '    }',
      '    if(lang==="fr"){',
      '      return s.replace(/Hi/g,"Salut")',
      '              .replace(/We noticed/g,"Nous avons remarqu\\u00E9")',
      '              .replace(/Pick up where you left off/g,"Reprenez votre commande")',
      '              .replace(/We\\u2019ll hold your cart/g,"Nous gardons votre panier");',
      '    }',
      '    return s;',
      '  }',
      '  function readCfg(){',
      '    function gv(id){ var e=document.getElementById(id); return e?e.value:""; }',
      '    function gc(id){ var e=document.getElementById(id); return !!(e && e.checked); }',
      '    return {',
      '      firstName: gv("firstName"),',
      '      productName: gv("productName"),',
      '      checkoutUrl: gv("checkoutUrl"),',
      '      tone: gv("tone"), channel: gv("channel"), length: gv("length"),',
      '      offer: gv("offer"), timing: gv("timing"), lang: (document.getElementById("lang")?gv("lang"):"en"),',
      '      cta: gv("ctaLabel") || "Resume checkout",',
      '      includeName: gc("tokName"), includeProd: gc("tokProd"), includeUrl: gc("tokUrl"), includeDisc: gc("tokDisc")',
      '    };',
      '  }',
      '  function update(){',
      '    var cfg = readCfg();',
      '    var text = baseCopy(cfg);',
      '    if(cfg.length==="Short"){ text = text.split("\\n").slice(0,2).join(" "); }',
      '    if(cfg.length==="Long"){ text = text + "\\nP.S. Your picks are popular\\u2014don\\u2019t miss your size."; }',
      '    text = localize(text, cfg.lang);',
      '    var chText = byChannel(text, cfg.channel, cfg.cta);',
      '    var b = altVariant(text);',
      '    var bCh = byChannel(localize(b, cfg.lang), cfg.channel, cfg.cta);',
      '    var p=document.getElementById("preview"); if(p) p.value = chText;',
      '    var pb=document.getElementById("previewB"); if(pb) pb.value = bCh;',
      '    var q = new URLSearchParams(cfg).toString(); history.replaceState(null,"","?"+q);',
      '  }',
      '  function calc(){',
      '    var aov=+document.getElementById("aov").value||0;',
      '    var sessions=+document.getElementById("sessions").value||0;',
      '    var aband=+document.getElementById("aband").value||0;',
      '    var rec=+document.getElementById("recovery").value||0;',
      '    var offer=document.getElementById("offer").value;',
      '    if(offer==="10% off"||offer==="$10 off") rec+=1.0;',
      '    if(offer==="Free shipping") rec+=0.5;',
      '    var carts = sessions * (aband/100);',
      '    var recovered = carts * (rec/100);',
      '    var revenue = recovered * aov;',
      '    document.getElementById("calcOut").textContent = "\\u2248 " + recovered.toFixed(0) + " carts / $" + revenue.toFixed(0) + " month";',
      '  }',
      '  function share(){',
      '    if(navigator.clipboard && navigator.clipboard.writeText){',
      '      navigator.clipboard.writeText(location.href).then(function(){ alert("Share link copied!"); });',
      '    }',
      '  }',
      '  function wire(){',
      '    var ids=["genBtn","abBtn","shareBtn","calcBtn"];',
      '    if(document.getElementById("genBtn")) document.getElementById("genBtn").onclick = update;',
      '    if(document.getElementById("shareBtn")) document.getElementById("shareBtn").onclick = share;',
      '    if(document.getElementById("calcBtn")) document.getElementById("calcBtn").onclick = calc;',
      '    var ch=["tone","channel","length","offer","timing","ctaLabel","firstName","productName","checkoutUrl","tokName","tokProd","tokUrl","tokDisc"];',
      '    for(var i=0;i<ch.length;i++){ var e=document.getElementById(ch[i]); if(e){ e.addEventListener("change",update); } }',
      '    // hydrate from query',
      '    var q=new URLSearchParams(location.search);',
      '    q.forEach(function(v,k){ var e=document.getElementById(k); if(!e) return; if(e.type==="checkbox"){ e.checked = (v==="true"||v==="1"); } else { e.value = v; } });',
      '    calc(); update();',
      '  }',
      '  wire();',
      '})();'
    );

    const __src = lines.join('\n');
    res.set('Content-Type','application/javascript; charset=utf-8').send(__src);
  });
}
