"use client";
import { useState } from "react";

const labels: Record<string, string> = { NEW: "New", CONSIDERING: "Considering", PURSUE: "Pursue", APPLIED: "Applied", INTERVIEWING: "Interviewing", OFFER: "Offer", REJECTED: "Rejected", WITHDRAWN: "Withdrawn", CLOSED: "Closed" };
const nextStates: Record<string, string[]> = { NEW: ["CONSIDERING", "CLOSED"], CONSIDERING: ["PURSUE", "WITHDRAWN", "CLOSED"], PURSUE: ["APPLIED", "WITHDRAWN", "CLOSED"], APPLIED: ["INTERVIEWING", "REJECTED", "WITHDRAWN", "CLOSED"], INTERVIEWING: ["OFFER", "REJECTED", "WITHDRAWN", "CLOSED"], OFFER: ["WITHDRAWN", "CLOSED"], REJECTED: ["CLOSED"], WITHDRAWN: ["CLOSED"], CLOSED: [] };
type Activity = { events: { id: string; eventType: string; createdAt: string }[]; notes: { id: string; content: string; createdAt: string }[] };
const eventLabels: Record<string, string> = { OPPORTUNITY_IMPORTED: "Opportunity imported", OPPORTUNITY_ANALYZED: "Job analyzed", OPPORTUNITY_DECISION_CHANGED: "Decision changed", APPLICATION_MARKED_APPLIED: "Marked applied", INTERVIEW_MARKED: "Marked interviewing", OFFER_MARKED: "Offer recorded", OPPORTUNITY_REJECTED: "Marked rejected", OPPORTUNITY_WITHDRAWN: "Opportunity withdrawn", OPPORTUNITY_CLOSED: "Opportunity closed", OPPORTUNITY_NOTE_ADDED: "Note added", OPPORTUNITY_LIFECYCLE_UPDATED: "Status updated" };

export default function OpportunityLifecyclePanel({ opportunityId, initialState, nextAction, activity }: { opportunityId: string; initialState: string; nextAction: string; activity: Activity }) {
  const [state, setState] = useState(initialState || "NEW"); const [note, setNote] = useState(""); const [message, setMessage] = useState("");
  async function update(value: string) { setMessage(""); const response = await fetch(`/api/career/opportunities/${opportunityId}`, { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ lifecycleState: value }) }); if (response.ok) { setState(value); setMessage("Status saved"); } else { const body = await response.json().catch(() => ({})); setMessage(body.error === "INVALID_LIFECYCLE_TRANSITION" ? "That status change is not available from the current status." : "We could not save the status. Try again."); } }
  async function saveNote(event: React.FormEvent) { event.preventDefault(); setMessage(""); const response = await fetch(`/api/career/opportunities/${opportunityId}`, { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ note }) }); if (response.ok) { setNote(""); setMessage("Note added"); } else setMessage("We could not add that note. Try again."); }
  return <section className="careerProfilePanel"><h2>What happens next?</h2><p className="careerMuted">{nextAction}</p><label>Status<select value={state} onChange={(event) => update(event.target.value)}><option value={state}>{labels[state] || state}</option>{(nextStates[state] || []).map((value) => <option key={value} value={value}>{labels[value]}</option>)}</select></label>{message && <p className="careerSaved" role="status">{message}</p>}<form className="careerForm" onSubmit={saveNote}><label>Add a note <span className="careerMuted">(optional, 2,000 characters max)<textarea value={note} maxLength={2000} onChange={(event) => setNote(event.target.value)} placeholder="Recruiter, interview date, or follow-up detail" /></span></label><button className="careerSmallButton" disabled={!note.trim()}>Add note</button></form>{(activity.notes.length > 0 || activity.events.length > 0) && <details><summary>Opportunity history</summary><div className="careerNav">{activity.notes.map((item) => <p key={item.id}><strong>Note:</strong> {item.content}</p>)}{activity.events.map((item) => <p className="careerMuted" key={item.id}>{eventLabels[item.eventType] || "Opportunity updated"} · {new Date(item.createdAt).toLocaleDateString()}</p>)}</div></details>}</section>;
}
