import { redirect } from "next/navigation";
import { currentCareerContext } from "../../../../lib/career/careerP0Auth";
import { getOpportunity } from "../../../../lib/career/careerP0Product.mjs";
import { hasAdditionalMatchEvidence, visibleMatchExplanationGroups } from "../../../../lib/career/matchExplanation.mjs";
import OpportunityDecisionPanel from "./OpportunityDecisionPanel";
import OpportunityLifecyclePanel from "./OpportunityLifecyclePanel";
export const runtime = "nodejs";
type MatchEvidence = { statement: string; sourceType?: string | null; sourceExcerpt?: string | null; scopeStatement?: string | null };
type MatchRelationship = { id: string; text: string; explanation: string; state: string; evidence?: MatchEvidence[] };
export default async function JobResultPage({ params }: { params: Promise<{ opportunityId: string }> }) {
  const context = await currentCareerContext(); if (!context) redirect("/career/login");
  const data = await getOpportunity(context, (await params).opportunityId);
  const relationships = data.match.relationships as MatchRelationship[]; const groups = new Map<string, MatchRelationship[]>(); for (const item of relationships) groups.set(item.state, [...(groups.get(item.state) || []), item]);
  const visibleGroups = visibleMatchExplanationGroups(relationships);
  const hasAdditionalGaps = hasAdditionalMatchEvidence(relationships);
  return <main className="careerShell"><header className="careerHeader"><div><p className="careerEyebrow">CareerOS match explanation</p><h1>{data.opportunity.title}</h1><p className="careerMuted">{data.opportunity.company || "User-supplied role"}{data.opportunity.location ? " · " + data.opportunity.location : ""}{data.opportunity.sourceUrl ? <> · <a href={data.opportunity.sourceUrl} target="_blank" rel="noreferrer">Source link</a></> : null}</p></div><span><a href="/career/jobs">Saved jobs</a>{data.opportunity.decisionState === "PURSUE" && <> · <a href={`/career/jobs/${data.opportunity.id}/application-evidence`}>Application evidence</a></>}</span></header><section className="careerProfilePanel"><h2>{data.match.stale ? "Previous match analysis" : "What CareerOS knows"}</h2><p>{data.match.summary.headline}</p><p className="careerMuted">This is an evidence-based explanation, not a promise or a decision about whether to apply.</p>{data.match.stale && <p className="careerWarning">Your career information has changed since this job was analyzed. Re-analyze the job before treating this evidence as current.</p>}{visibleGroups.map(([key, label]) => <div className="careerResultGroup" key={key}><h3>{label}</h3>{groups.get(key)!.map((item) => <article className="careerCandidate" key={item.id}><strong>{item.text}</strong><p className="careerMuted">{item.explanation}</p>{!data.match.stale && item.evidence && item.evidence.length > 0 && <details><summary>How CareerOS knows this</summary>{item.evidence.map((evidence, index) => <div className="careerEvidence" key={index}><p>{evidence.statement}</p>{evidence.sourceType && <p className="careerMuted">Source: {evidence.sourceType}</p>}{evidence.scopeStatement && <p className="careerMuted">Scope: {evidence.scopeStatement}</p>}{evidence.sourceExcerpt && <p className="careerMuted">Source excerpt: {evidence.sourceExcerpt}</p>}</div>)}</details>}</article>)}</div>)}{!hasAdditionalGaps && <p className="careerMuted">No additional evidence gaps or specialist constraints were identified in this analysis.</p>}</section><OpportunityDecisionPanel opportunityId={data.opportunity.id} initialDecision={data.opportunity.decisionState} stale={Boolean(data.match.stale)} /><OpportunityLifecyclePanel opportunityId={data.opportunity.id} initialState={data.opportunity.lifecycleState} nextAction={data.opportunity.nextAction} activity={data.activity} /></main>;
}
