import { redirect } from "next/navigation";
import { currentCareerContext } from "../../../../lib/career/careerP0Auth";
import { getOpportunity } from "../../../../lib/career/careerP0Product.mjs";
import OpportunityDecisionPanel from "./OpportunityDecisionPanel";
export const runtime = "nodejs";
type MatchRelationship = { id: string; text: string; explanation: string; state: string };
export default async function JobResultPage({ params }: { params: Promise<{ opportunityId: string }> }) {
  const context = await currentCareerContext(); if (!context) redirect("/career/login");
  const data = await getOpportunity(context, (await params).opportunityId);
  const relationships = data.match.relationships as MatchRelationship[]; const groups = new Map<string, MatchRelationship[]>(); for (const item of relationships) groups.set(item.state, [...(groups.get(item.state) || []), item]);
  return <main className="careerShell"><header className="careerHeader"><div><p className="careerEyebrow">CareerOS match explanation</p><h1>{data.opportunity.title}</h1><p className="careerMuted">{data.opportunity.company || "User-supplied role"}{data.opportunity.location ? " · " + data.opportunity.location : ""}{data.opportunity.sourceUrl ? <> · <a href={data.opportunity.sourceUrl} target="_blank" rel="noreferrer">Source link</a></> : null}</p></div><a href="/career/jobs">Saved jobs</a></header><section className="careerProfilePanel"><h2>What CareerOS knows</h2><p>{data.match.summary.headline}</p><p className="careerMuted">This is a capability explanation, not a promise or a decision about whether to apply.</p>{data.match.stale && <p className="careerWarning">Your career information has changed since this job was analyzed. Re-analyze the job below to refresh the explanation.</p>}{[["DIRECT", "What looks strong"], ["TRANSFERABLE", "Transferable strengths"], ["PARTIAL", "Partial evidence"], ["UNKNOWN", "What needs more evidence"], ["SPECIALIST_BLOCKED", "Specialist requirements"]].map(([key, label]) => <div className="careerResultGroup" key={key}><h3>{label}</h3>{(groups.get(key) || []).length === 0 ? <p className="careerMuted">None identified.</p> : groups.get(key)!.map((item) => <article className="careerCandidate" key={item.id}><strong>{item.text}</strong><p className="careerMuted">{item.explanation}</p></article>)}</div>)}</section><OpportunityDecisionPanel opportunityId={data.opportunity.id} initialDecision={data.opportunity.decisionState} stale={Boolean(data.match.stale)} /><section className="careerProfilePanel"><h2>Next step</h2><p className="careerMuted">{data.match.summary.unknown > 0 ? "Add experience if you have relevant evidence CareerOS does not know yet." : "Return to Saved jobs any time to review this role or add another one."}</p></section></main>;
}
