"use client";

import { useEffect, useState } from "react";

type Candidate = { candidateFactId: string; factType: string; statement: string; sourceExcerpt: string; status: string; sourceType: string; scopeStatement: string | null };

const SOURCE_TYPES = ["RESUME_TEXT", "MANUAL_WORK_HISTORY", "PROJECT", "CERTIFICATION", "PORTFOLIO_DESCRIPTION", "OTHER_USER_PROVIDED_TEXT"];

export function IntakeReview() {
  const [sourceType, setSourceType] = useState(SOURCE_TYPES[0]);
  const [text, setText] = useState("");
  const [candidates, setCandidates] = useState<Candidate[]>([]);
  const [stage, setStage] = useState("CAREER_SOURCE");
  const [message, setMessage] = useState("");
  const [busy, setBusy] = useState(false);
  async function refresh() { const response = await fetch("/api/career/intake/candidates", { cache: "no-store" }); if (!response.ok) return; const result = await response.json(); setCandidates(result.candidates || []); setStage(result.onboarding?.stage || "CAREER_SOURCE"); }
  useEffect(() => { refresh(); }, []);
  async function submitSource(event: React.FormEvent) { event.preventDefault(); setBusy(true); setMessage(""); const response = await fetch("/api/career/intake/source", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ sourceType, text }) }); const result = await response.json(); setBusy(false); if (!response.ok) { setMessage(result.error || "Source was not processed."); return; } setText(""); setMessage(`${result.candidates.length} candidate facts created.`); await refresh(); }
  async function review(candidateId: string, decision: string) { let correction; if (decision === "CORRECT") { correction = window.prompt("Edit the proposed fact", candidates.find((candidate) => candidate.candidateFactId === candidateId)?.statement || ""); if (!correction) return; } const response = await fetch(`/api/career/intake/candidates/${encodeURIComponent(candidateId)}`, { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ decision, correction }) }); if (response.ok) { setMessage("Review saved."); await refresh(); } else setMessage("Review was not saved."); }
  return <section className="careerProfilePanel"><p className="careerEyebrow">Career intake</p><h2>{stage === "FACT_REVIEW" ? "Confirm your career facts" : "Add career information"}</h2><p className="careerMuted">CareerOS proposes source-backed facts for your review. Confirming a fact does not create a capability or match result yet.</p><form onSubmit={submitSource} className="careerForm"><label>Source type<select value={sourceType} onChange={(event) => setSourceType(event.target.value)}>{SOURCE_TYPES.map((type) => <option key={type}>{type}</option>)}</select></label><label>Paste career text<textarea value={text} onChange={(event) => setText(event.target.value)} required maxLength={50000} placeholder="Paste a resume section, project description, or work history here." /></label><button className="careerPrimaryButton" disabled={busy}>{busy ? "Processing..." : "Find candidate facts"}</button></form>{message ? <p className="careerSaved" role="status">{message}</p> : null}<div className="careerCandidateList">{candidates.map((candidate) => <article key={candidate.candidateFactId} className="careerCandidate"><div><span className="careerEyebrow">{candidate.factType} · {candidate.status}</span><h3>{candidate.statement}</h3><p className="careerMuted">Source excerpt: “{candidate.sourceExcerpt}”</p>{candidate.scopeStatement ? <p className="careerMuted">Scope stated: {candidate.scopeStatement}</p> : null}</div>{candidate.status === "PROPOSED" || candidate.status === "NEEDS_REVIEW" ? <div className="careerCandidateActions"><button className="careerSmallButton" onClick={() => review(candidate.candidateFactId, "CONFIRM")}>Confirm</button><button className="careerSmallButton" onClick={() => review(candidate.candidateFactId, "CORRECT")}>Correct</button><button className="careerSmallButton" onClick={() => review(candidate.candidateFactId, "REJECT")}>Reject</button><button className="careerSmallButton" onClick={() => review(candidate.candidateFactId, "KEEP_FOR_LATER")}>Later</button></div> : <p className="careerMuted">Review saved: {candidate.status}</p>}</article>)}</div></section>;
}
