"use client";

import Link from "next/link";
import { FormEvent, useState } from "react";
import { useRouter } from "next/navigation";

type Profile = { displayName: string; headline: string | null; location: string | null; careerStage: string | null; version?: number };

export function ProfileForm({ initialProfile, email, mode }: { initialProfile: Profile | null; email: string; mode: "onboarding" | "profile" }) {
  const router = useRouter();
  const [profile, setProfile] = useState({ displayName: initialProfile?.displayName || "", headline: initialProfile?.headline || "", location: initialProfile?.location || "", careerStage: initialProfile?.careerStage || "" });
  const [message, setMessage] = useState(""); const [busy, setBusy] = useState(false);
  async function submit(event: FormEvent) { event.preventDefault(); setBusy(true); setMessage(""); const response = await fetch("/api/career/profile", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify(profile) }); const result = await response.json(); setBusy(false); if (!response.ok) { setMessage("Profile was not saved."); return; } setProfile({ displayName: result.profile.displayName || "", headline: result.profile.headline || "", location: result.profile.location || "", careerStage: result.profile.careerStage || "" }); setMessage("SAVED"); router.refresh(); }
  async function logout() { await fetch("/api/career/auth/logout", { method: "POST" }); router.push("/career/login"); router.refresh(); }
  return <main className="careerShell"><header className="careerHeader"><div><p className="careerEyebrow">CareerOS</p><h1>{mode === "onboarding" ? "Start your career profile" : "Your career profile"}</h1><p className="careerMuted">Signed in as {email}. This profile is private to your account.</p></div><button className="careerLinkButton" onClick={logout}>Log out</button></header><section className="careerProfilePanel"><p className="careerEyebrow">Profile foundation</p><h2>{mode === "onboarding" ? "Tell CareerOS where to begin" : "Profile details"}</h2><p className="careerMuted">This first step stores identity and profile ownership only. Career sources and capability review come later.</p><form onSubmit={submit} className="careerForm"><label>Display name<input required value={profile.displayName} onChange={(event) => setProfile({ ...profile, displayName: event.target.value })} /></label><label>Headline <span>(optional)</span><input value={profile.headline} onChange={(event) => setProfile({ ...profile, headline: event.target.value })} /></label><label>Location <span>(optional)</span><input value={profile.location} onChange={(event) => setProfile({ ...profile, location: event.target.value })} /></label><label>Career stage <span>(optional)</span><input value={profile.careerStage} onChange={(event) => setProfile({ ...profile, careerStage: event.target.value })} /></label>{message ? <p className={message === "SAVED" ? "careerSaved" : "careerError"} role="status">{message}</p> : null}<button className="careerPrimaryButton" disabled={busy}>{busy ? "Saving..." : mode === "onboarding" ? "Create profile" : "Save profile"}</button></form><nav className="careerNav"><Link href="/career/profile">Profile</Link></nav></section></main>;
}
