import crypto from "node:crypto";
import pg from "pg";

const { Pool } = pg;
const SESSION_TTL_MS = 1000 * 60 * 60 * 24 * 30;

function id(prefix) { return `${prefix}_${crypto.randomUUID()}`; }
function now() { return new Date(); }
function email(value) { return String(value || "").trim().toLowerCase(); }
function digest(value) { return crypto.createHash("sha256").update(`${process.env.CAREEROS_SESSION_PEPPER || ""}:${String(value)}`).digest("hex"); }
async function passwordHash(password, salt = crypto.randomBytes(16).toString("hex")) {
  const key = await new Promise((resolve, reject) => crypto.scrypt(String(password), salt, 64, (error, result) => error ? reject(error) : resolve(result)));
  return { salt, hash: Buffer.from(key).toString("hex") };
}
async function passwordMatches(password, row) {
  const candidate = await passwordHash(password, row["passwordSalt"]);
  const actual = Buffer.from(candidate.hash, "hex"); const expected = Buffer.from(row["passwordHash"], "hex");
  return actual.length === expected.length && crypto.timingSafeEqual(actual, expected);
}
function profile(row) { return row ? { id: row.id, tenantId: row["tenantId"], userId: row["userId"], displayName: row["displayName"], headline: row.headline, location: row.location, careerStage: row["careerStage"], status: row.status, version: row.version, createdAt: row["createdAt"], updatedAt: row["updatedAt"] } : null; }
function candidate(row) { return row ? { candidateFactId: row["candidateFactId"], sourceId: row["sourceId"], sourceType: row.sourceType, factType: row["factType"], statement: row.statement, sourceExcerpt: row["sourceExcerpt"], sourceOrder: row["sourceOrder"], scopeStatement: row["scopeStatement"], extractionMethod: row["extractionMethod"], extractionVersion: row["extractionVersion"], confidence: row.confidence, ambiguity: row.ambiguity, status: row.status, createdAt: row["createdAt"], updatedAt: row["updatedAt"] } : null; }

export function createCareerP0PostgresStore({ connectionString = process.env.DATABASE_URL, pool: providedPool = null } = {}) {
  if (!connectionString) throw new Error("CAREEROS_DATABASE_URL_REQUIRED");
  const pool = providedPool || new Pool({ connectionString, max: Number(process.env.CAREEROS_DB_POOL_MAX || 10), connectionTimeoutMillis: 5000, idleTimeoutMillis: 30000 });

  async function transaction(work) { const client = await pool.connect(); try { await client.query("BEGIN"); const result = await work(client); await client.query("COMMIT"); return result; } catch (error) { await client.query("ROLLBACK"); throw error; } finally { client.release(); } }
  async function context(sessionId, client = pool) {
    if (!sessionId) return null;
    const result = await client.query('SELECT s.*, u.id AS "userId", u.email, t.id AS "tenantId", t.name AS "tenantName" FROM "CareerSession" s JOIN "CareerUser" u ON u.id = s."userId" JOIN "CareerTenantMembership" m ON m."userId" = s."userId" AND m."tenantId" = s."tenantId" JOIN "CareerTenant" t ON t.id = s."tenantId" WHERE s."tokenDigest" = $1 AND s."revokedAt" IS NULL AND s."expiresAt" > NOW() LIMIT 1', [digest(sessionId)]);
    const row = result.rows[0]; if (!row) return null;
    await client.query('UPDATE "CareerSession" SET "lastUsedAt" = NOW() WHERE id = $1', [row.id]);
    return { session: { id: sessionId, dbId: row.id, expiresAt: row["expiresAt"] }, user: { id: row["userId"], email: row.email }, tenant: { id: row["tenantId"], name: row["tenantName"] }, membership: { tenantId: row["tenantId"], userId: row["userId"], role: "OWNER" } };
  }
  async function session(client, userId, tenantId) { const raw = crypto.randomBytes(32).toString("base64url"); await client.query('INSERT INTO "CareerSession" ("id", "tokenDigest", "userId", "tenantId", "expiresAt") VALUES ($1,$2,$3,$4,$5)', [id("session"), digest(raw), userId, tenantId, new Date(Date.now() + SESSION_TTL_MS)]); return raw; }
  async function audit(client, tenantId, userId, eventType, entityType = null, entityId = null, metadata = null) { await client.query('INSERT INTO "CareerAuditEvent" ("id", "tenantId", "userId", "eventType", "entityType", "entityId", "metadata") VALUES ($1,$2,$3,$4,$5,$6,$7)', [id("audit"), tenantId, userId, eventType, entityType, entityId, metadata]); }

  async function consumeRateLimit(key, { limit = 10, windowMs = 60_000 } = {}) {
    if (!key || !Number.isFinite(limit) || !Number.isFinite(windowMs)) return { allowed: false, remaining: 0 };
    return transaction(async (client) => {
      const result = await client.query('SELECT "windowStartedAt", count FROM "CareerRateLimitBucket" WHERE key=$1 FOR UPDATE', [String(key).slice(0, 240)]);
      const current = result.rows[0]; const nowMs = Date.now();
      if (!current || nowMs - new Date(current["windowStartedAt"]).getTime() >= windowMs) {
        await client.query('INSERT INTO "CareerRateLimitBucket" (key,"windowStartedAt",count,"updatedAt") VALUES ($1,NOW(),1,NOW()) ON CONFLICT (key) DO UPDATE SET "windowStartedAt"=NOW(),count=1,"updatedAt"=NOW()', [String(key).slice(0, 240)]);
        return { allowed: true, remaining: Math.max(0, limit - 1) };
      }
      if (Number(current.count) >= limit) return { allowed: false, remaining: 0 };
      await client.query('UPDATE "CareerRateLimitBucket" SET count=count+1,"updatedAt"=NOW() WHERE key=$1', [String(key).slice(0, 240)]);
      return { allowed: true, remaining: Math.max(0, limit - Number(current.count) - 1) };
    });
  }

  async function createInvite({ email: inviteEmail, ttlMs = 1000 * 60 * 60 * 24 * 7 } = {}) {
    const normalized = email(inviteEmail); if (!normalized || !normalized.includes("@")) throw Object.assign(new Error("invalid_invite_email"), { code: "INVALID_INVITE_EMAIL" });
    const raw = crypto.randomBytes(32).toString("base64url"); const inviteId = id("invite");
    await pool.query('INSERT INTO "CareerInvite" ("id",email,"tokenDigest","expiresAt") VALUES ($1,$2,$3,$4)', [inviteId, normalized, digest(raw), new Date(Date.now() + ttlMs)]);
    return { inviteId, email: normalized, token: raw };
  }

  async function createAccount(input) {
    const normalized = email(input.email); if (!normalized || !normalized.includes("@") || String(input.password || "").length < 8) throw Object.assign(new Error("invalid_account_input"), { code: "INVALID_ACCOUNT_INPUT" });
    return transaction(async (client) => { const existing = await client.query('SELECT id FROM "CareerUser" WHERE email = $1', [normalized]); if (existing.rowCount) throw Object.assign(new Error("account_exists"), { code: "ACCOUNT_EXISTS" }); const inviteOnly = String(process.env.CAREEROS_INVITE_ONLY || "").toLowerCase() === "true"; let invite = null; if (inviteOnly) { invite = (await client.query('SELECT * FROM "CareerInvite" WHERE "tokenDigest"=$1 AND lower(email)=$2 AND "consumedAt" IS NULL AND "expiresAt">NOW() FOR UPDATE', [digest(input.inviteToken || ""), normalized])).rows[0]; if (!invite) throw Object.assign(new Error("invite_required"), { code: "INVITE_REQUIRED" }); } const hashed = await passwordHash(input.password); const userId = id("user"); const tenantId = id("tenant"); const displayName = String(input.displayName || normalized.split("@")[0]).trim() || "CareerOS profile"; await client.query('INSERT INTO "CareerUser" ("id", email, "passwordHash", "passwordSalt", "updatedAt") VALUES ($1,$2,$3,$4,NOW())', [userId, normalized, hashed.hash, hashed.salt]); await client.query('INSERT INTO "CareerTenant" ("id", name, "updatedAt") VALUES ($1,$2,NOW())', [tenantId, displayName]); await client.query('INSERT INTO "CareerTenantMembership" ("id", "tenantId", "userId") VALUES ($1,$2,$3)', [id("membership"), tenantId, userId]); if (invite) await client.query('UPDATE "CareerInvite" SET "consumedAt"=NOW() WHERE id=$1', [invite.id]); await audit(client, tenantId, userId, "ACCOUNT_CREATED"); return { sessionId: await session(client, userId, tenantId), user: { id: userId, email: normalized }, tenant: { id: tenantId, name: displayName } }; });
  }
  async function login(input) { return transaction(async (client) => { const result = await client.query('SELECT * FROM "CareerUser" WHERE email = $1 LIMIT 1', [email(input.email)]); const user = result.rows[0]; if (!user || !(await passwordMatches(input.password, user))) throw Object.assign(new Error("invalid_credentials"), { code: "INVALID_CREDENTIALS" }); const membership = await client.query('SELECT m.*, t.name FROM "CareerTenantMembership" m JOIN "CareerTenant" t ON t.id = m."tenantId" WHERE m."userId" = $1 AND m.role = \'OWNER\' LIMIT 1', [user.id]); const member = membership.rows[0]; if (!member) throw Object.assign(new Error("tenant_membership_missing"), { code: "TENANT_MEMBERSHIP_MISSING" }); await audit(client, member["tenantId"], user.id, "LOGIN"); return { sessionId: await session(client, user.id, member["tenantId"]), user: { id: user.id, email: user.email }, tenant: { id: member["tenantId"], name: member.name } }; }); }
  async function resolveSession(raw) { return context(raw); }
  async function destroySession(raw) { const ctx = await context(raw); if (ctx) await pool.query('UPDATE "CareerSession" SET "revokedAt" = NOW() WHERE id = $1', [ctx.session.dbId]); }
  async function getProfile(raw) { const ctx = await context(raw); if (!ctx) return null; const result = await pool.query('SELECT * FROM "CareerProfile" WHERE id IN (SELECT id FROM "CareerProfile" WHERE "tenantId" = $1 AND "userId" = $2) LIMIT 1', [ctx.tenant.id, ctx.user.id]); return profile(result.rows[0]); }
  async function saveProfile(raw, input) { const ctx = await context(raw); if (!ctx) throw Object.assign(new Error("unauthorized"), { code: "UNAUTHORIZED" }); return transaction(async (client) => { const current = await client.query('SELECT * FROM "CareerProfile" WHERE "tenantId" = $1 AND "userId" = $2 LIMIT 1', [ctx.tenant.id, ctx.user.id]); const clean = (value) => value == null ? null : String(value).trim().slice(0, 240) || null; let row; if (!current.rowCount) { row = (await client.query('INSERT INTO "CareerProfile" ("id", "tenantId", "userId", "displayName", headline, location, "careerStage", "updatedAt") VALUES ($1,$2,$3,$4,$5,$6,$7,NOW()) RETURNING *', [id("profile"), ctx.tenant.id, ctx.user.id, clean(input.displayName) || ctx.user.email.split("@")[0], clean(input.headline), clean(input.location), clean(input.careerStage)])).rows[0]; await client.query('INSERT INTO "CareerOnboardingState" ("id", "tenantId", "profileId", "updatedAt") VALUES ($1,$2,$3,NOW())', [id("onboarding"), ctx.tenant.id, row.id]); } else { row = (await client.query('UPDATE "CareerProfile" SET "displayName"=$1,headline=$2,location=$3,"careerStage"=$4,version=version+1,"updatedAt"=NOW() WHERE "tenantId"=$5 AND "userId"=$6 RETURNING *', [clean(input.displayName) || current.rows[0]["displayName"], input.headline === undefined ? current.rows[0].headline : clean(input.headline), input.location === undefined ? current.rows[0].location : clean(input.location), input.careerStage === undefined ? current.rows[0]["careerStage"] : clean(input.careerStage), ctx.tenant.id, ctx.user.id])).rows[0]; } await audit(client, ctx.tenant.id, ctx.user.id, "PROFILE_UPDATED", "CareerProfile", row.id); return profile(row); }); }
  async function listSources(raw) { const ctx = await context(raw); if (!ctx) throw Object.assign(new Error("unauthorized"), { code: "UNAUTHORIZED" }); const result = await pool.query('SELECT id,"tenantId","userId","profileId","sourceType","sourceStatus","originalFilename","contentReference","sourceDigest","extractorVersion","createdAt","updatedAt" FROM "CareerSource" WHERE "tenantId"=$1 AND "userId"=$2 ORDER BY "createdAt" DESC', [ctx.tenant.id, ctx.user.id]); return result.rows; }
  async function createSource(raw, input) { const ctx = await context(raw); if (!ctx) throw Object.assign(new Error("unauthorized"), { code: "UNAUTHORIZED" }); return transaction(async (client) => { const p = await client.query('SELECT id FROM "CareerProfile" WHERE "tenantId"=$1 AND "userId"=$2 LIMIT 1', [ctx.tenant.id, ctx.user.id]); if (!p.rowCount) throw Object.assign(new Error("profile_required"), { code: "PROFILE_REQUIRED" }); const text = input.textContent == null ? null : String(input.textContent).trim().slice(0, 50000); const row = (await client.query('INSERT INTO "CareerSource" ("id","tenantId","userId","profileId","sourceType","sourceStatus","originalFilename","contentReference","textContent","updatedAt") VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,NOW()) RETURNING id,"tenantId","userId","profileId","sourceType","sourceStatus","originalFilename","contentReference","createdAt","updatedAt"', [id("source"), ctx.tenant.id, ctx.user.id, p.rows[0].id, input.sourceType, text ? "STORED" : "PENDING_STORAGE", input.originalFilename || null, null, text])).rows[0]; await audit(client, ctx.tenant.id, ctx.user.id, "SOURCE_CREATED", "CareerSource", row.id); return row; }); }
  async function getSource(raw, sourceId) { const ctx = await context(raw); if (!ctx) throw Object.assign(new Error("unauthorized"), { code: "UNAUTHORIZED" }); const result = await pool.query('SELECT id,"tenantId","userId","profileId","sourceType","sourceStatus","originalFilename","contentReference","sourceDigest","extractorVersion","textContent","createdAt","updatedAt" FROM "CareerSource" WHERE id=$1 AND "tenantId"=$2 AND "userId"=$3', [sourceId, ctx.tenant.id, ctx.user.id]); return result.rows[0] || null; }
  async function saveCandidates(raw, sourceId, extraction) { const ctx = await context(raw); if (!ctx) throw Object.assign(new Error("unauthorized"), { code: "UNAUTHORIZED" }); return transaction(async (client) => { const source = (await client.query('SELECT * FROM "CareerSource" WHERE id=$1 AND "tenantId"=$2 AND "userId"=$3', [sourceId, ctx.tenant.id, ctx.user.id])).rows[0]; if (!source) throw Object.assign(new Error("source_not_found"), { code: "SOURCE_NOT_FOUND" }); await client.query('UPDATE "CareerSource" SET "sourceDigest"=$1,"extractorVersion"=$2,"sourceStatus"=\'READY\',"updatedAt"=NOW() WHERE id=$3 AND "tenantId"=$4', [extraction.sourceDigest, extraction.extractorVersion, sourceId, ctx.tenant.id]); for (const item of extraction.candidates) await client.query('INSERT INTO "CareerFactCandidate" ("id","candidateFactId","tenantId","userId","profileId","sourceId","factType","statement","sourceExcerpt","sourceOrder","scopeStatement","extractionMethod","extractionVersion","confidence","ambiguity","updatedAt") VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14,$15,NOW()) ON CONFLICT ("sourceId","extractionVersion","sourceOrder") DO NOTHING', [id("candidate"), item.candidateFactId, ctx.tenant.id, ctx.user.id, source["profileId"], sourceId, item.factType, item.statement, item.sourceExcerpt, item.sourceOrder, item.scopeStatement, item.extractionMethod, item.extractionVersion, item.confidence, JSON.stringify(item.ambiguity)]); const result = await client.query('SELECT * FROM "CareerFactCandidate" WHERE "sourceId"=$1 AND "tenantId"=$2 AND "userId"=$3 ORDER BY "sourceOrder"', [sourceId, ctx.tenant.id, ctx.user.id]); return result.rows.map(candidate); }); }
  async function listCandidateFacts(raw) { const ctx = await context(raw); if (!ctx) throw Object.assign(new Error("unauthorized"), { code: "UNAUTHORIZED" }); const result = await pool.query('SELECT * FROM "CareerFactCandidate" WHERE "tenantId"=$1 AND "userId"=$2 ORDER BY "createdAt"', [ctx.tenant.id, ctx.user.id]); return result.rows.map(candidate); }
  async function reviewCandidate(raw, candidateId, decision, correction = null) { const ctx = await context(raw); if (!ctx) throw Object.assign(new Error("unauthorized"), { code: "UNAUTHORIZED" }); return transaction(async (client) => { const row = (await client.query('SELECT * FROM "CareerFactCandidate" WHERE "candidateFactId"=$1 AND "tenantId"=$2 AND "userId"=$3 FOR UPDATE', [candidateId, ctx.tenant.id, ctx.user.id])).rows[0]; if (!row) throw Object.assign(new Error("candidate_not_found"), { code: "CANDIDATE_NOT_FOUND" }); const next = decision === "CORRECT" ? String(correction || "").trim().slice(0, 500) : row.statement; if (decision === "CORRECT" && !next) throw Object.assign(new Error("correction_required"), { code: "CORRECTION_REQUIRED" }); const status = decision === "CONFIRM" ? "CONFIRMED" : decision === "CORRECT" ? "CORRECTED" : decision === "REJECT" ? "REJECTED" : "NEEDS_REVIEW"; await client.query('INSERT INTO "CareerFactReviewDecision" ("id","tenantId","userId","candidateFactId","decision","previousStatement","activeStatement") VALUES ($1,$2,$3,$4,$5,$6,$7)', [id("review"), ctx.tenant.id, ctx.user.id, candidateId, decision, row.statement, next]); const updated = (await client.query('UPDATE "CareerFactCandidate" SET statement=$1,status=$2,"updatedAt"=NOW() WHERE "candidateFactId"=$3 AND "tenantId"=$4 RETURNING *', [next, status, candidateId, ctx.tenant.id])).rows[0]; let fact = null; if (["CONFIRM", "CORRECT"].includes(decision)) fact = (await client.query('INSERT INTO "CareerFact" ("id","candidateFactId","tenantId","userId","profileId","sourceId","factType","statement","sourceExcerpt","sourceOrder","scopeStatement","authorityState","updatedAt") VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,NOW()) ON CONFLICT ("candidateFactId") DO UPDATE SET statement=EXCLUDED.statement,"updatedAt"=NOW() RETURNING *', [id("fact"), candidateId, ctx.tenant.id, ctx.user.id, row["profileId"], row["sourceId"], row["factType"], next, row["sourceExcerpt"], row["sourceOrder"], row["scopeStatement"], "CUSTOMER_CONFIRMED_SOURCE_BACKED"])).rows[0]; await audit(client, ctx.tenant.id, ctx.user.id, `FACT_${decision}`, "CareerFactCandidate", candidateId); return { candidate: candidate(updated), careerFact: fact }; }); }
  async function listCareerFacts(raw) { const ctx = await context(raw); if (!ctx) throw Object.assign(new Error("unauthorized"), { code: "UNAUTHORIZED" }); const result = await pool.query('SELECT * FROM "CareerFact" WHERE "tenantId"=$1 AND "userId"=$2 ORDER BY "createdAt"', [ctx.tenant.id, ctx.user.id]); return result.rows; }
  async function getOnboardingState(raw) { const ctx = await context(raw); if (!ctx) throw Object.assign(new Error("unauthorized"), { code: "UNAUTHORIZED" }); const result = await pool.query('SELECT p.id, (SELECT COUNT(*) FROM "CareerSource" s WHERE s."profileId"=p.id) AS sources, (SELECT COUNT(*) FROM "CareerFactCandidate" c WHERE c."profileId"=p.id) AS candidates, (SELECT COUNT(*) FROM "CareerFact" f WHERE f."profileId"=p.id) AS facts FROM "CareerProfile" p WHERE p."tenantId"=$1 AND p."userId"=$2', [ctx.tenant.id, ctx.user.id]); const row = result.rows[0]; if (!row) return { stage: "PROFILE", sourceCount: 0, candidateCount: 0, confirmedFactCount: 0 }; const stage = Number(row.sources) === 0 ? "CAREER_SOURCE" : Number(row.candidates) > Number(row.facts) ? "FACT_REVIEW" : "READY_FOR_CAPABILITIES"; return { stage, sourceCount: Number(row.sources), candidateCount: Number(row.candidates), confirmedFactCount: Number(row.facts) }; }
  async function deleteAccount(raw) { const ctx = await context(raw); if (!ctx) throw Object.assign(new Error("unauthorized"), { code: "UNAUTHORIZED" }); await transaction(async (client) => { await client.query('DELETE FROM "CareerTenant" WHERE id=$1', [ctx.tenant.id]); await client.query('DELETE FROM "CareerUser" WHERE id=$1', [ctx.user.id]); }); }
  async function exportAccount(raw) { const ctx = await context(raw); if (!ctx) throw Object.assign(new Error("unauthorized"), { code: "UNAUTHORIZED" }); const [p, s, c, r, f, o] = await Promise.all([pool.query('SELECT id,"displayName",headline,location,"careerStage",status,version,"createdAt","updatedAt" FROM "CareerProfile" WHERE "tenantId"=$1 AND "userId"=$2', [ctx.tenant.id, ctx.user.id]), pool.query('SELECT id,"sourceType","sourceStatus","originalFilename","sourceDigest","extractorVersion","createdAt","updatedAt" FROM "CareerSource" WHERE "tenantId"=$1 AND "userId"=$2', [ctx.tenant.id, ctx.user.id]), pool.query('SELECT "candidateFactId","sourceId","factType",statement,"sourceExcerpt","sourceOrder","status","createdAt","updatedAt" FROM "CareerFactCandidate" WHERE "tenantId"=$1 AND "userId"=$2', [ctx.tenant.id, ctx.user.id]), pool.query('SELECT "candidateFactId",decision,"previousStatement","activeStatement","createdAt" FROM "CareerFactReviewDecision" WHERE "tenantId"=$1 AND "userId"=$2', [ctx.tenant.id, ctx.user.id]), pool.query('SELECT id,"sourceId","factType",statement,"sourceExcerpt","sourceOrder","scopeStatement","authorityState",status,"createdAt","updatedAt" FROM "CareerFact" WHERE "tenantId"=$1 AND "userId"=$2', [ctx.tenant.id, ctx.user.id]), pool.query('SELECT stage,"updatedAt" FROM "CareerOnboardingState" WHERE "tenantId"=$1', [ctx.tenant.id])]); await pool.query('INSERT INTO "CareerAuditEvent" ("id","tenantId","userId","eventType") VALUES ($1,$2,$3,$4)', [id("audit"), ctx.tenant.id, ctx.user.id, "EXPORT_REQUESTED"]); return { profile: p.rows, sources: s.rows, candidates: c.rows, reviews: r.rows, careerFacts: f.rows, onboarding: o.rows }; }
  return { createAccount, createInvite, login, resolveSession, destroySession, consumeRateLimit, getProfile, saveProfile, listSources, createSource, getSource, saveCandidates, listCandidateFacts, reviewCandidate, listCareerFacts, getOnboardingState, deleteAccount, exportAccount, _pool: pool };
}
