name: Frontend smoke (Vite + Pages base)
on:
  pull_request:
    paths:
      - "web/frontend/**"
      - ".github/workflows/frontend-smoke.yml"
  workflow_dispatch: {}

jobs:
  smoke:
    runs-on: ubuntu-latest
    env:
      HUSKY: "0"
      npm_config_ignore_scripts: "true"
      NPM_CONFIG_FUND: "false"
      NPM_CONFIG_AUDIT: "false"
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
          cache-dependency-path: web/frontend/package-lock.json

      - name: Install deps
        run: |
          if [ -f web/frontend/package-lock.json ]; then
            npm --prefix web/frontend ci
          else
            npm --prefix web/frontend install
          fi

      - name: Build like GitHub Pages (subpath base) + SPA 404
        run: |
          REPO="$(basename "$GITHUB_REPOSITORY")"
          npm --prefix web/frontend run build -- --base="/$REPO/"
          cp web/frontend/dist/index.html web/frontend/dist/404.html || true

      - name: Preview & curl smoke
        run: |
          set -euo pipefail
          REPO="$(basename "$GITHUB_REPOSITORY")"
          npx vite preview --port 4173 --strictPort --host 127.0.0.1 \
            --open false --base "/$REPO/" > preview.log 2>&1 &
          PID=$!
          for i in {1..30}; do
            curl -fsS "http://127.0.0.1:4173/$REPO/" >/dev/null && break || sleep 1
          done
          code=$(curl -sS -o /dev/null -w "%{http_code}" "http://127.0.0.1:4173/$REPO/")
          html=$(curl -fsS "http://127.0.0.1:4173/$REPO/" || true)
          echo "HTTP: $code"
          grep -q "/$REPO/assets/" <<<"$html"
          kill $PID || true

      - name: Upload preview log on failure
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: preview-log
          path: preview.log
