name: Frontend preview smoke

on:
  push:
    branches: ["**"]
  pull_request:
    branches: ["**"]
  workflow_dispatch: {}

jobs:
  preview:
    runs-on: ubuntu-latest
    env:
      HUSKY: "0"
      npm_config_ignore_scripts: "true"
      NPM_CONFIG_FUND: "false"
      NPM_CONFIG_AUDIT: "false"
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: web/frontend/package-lock.json

      - name: Install (web/frontend)
        run: |
          if [ -f web/frontend/package-lock.json ]; then
            npm --prefix web/frontend ci
          else
            echo "⚠️ No lockfile; using npm install"
            npm --prefix web/frontend install
          fi

      - name: Build (web/frontend)
        env:
          VITE_RUN_ID: ${{ github.run_id }}
          VITE_RUN_NUMBER: ${{ github.run_number }}
        run: npm --prefix web/frontend run build

      - name: Serve preview in background and curl it
        working-directory: web/frontend
        shell: bash
        run: |
          set -euo pipefail
          npx vite preview --port 4173 --strictPort --host 127.0.0.1 > preview.log 2>&1 &
          echo $! > preview.pid
          echo "Waiting for http://127.0.0.1:4173 …"
          for i in {1..30}; do
            if curl -fsS http://127.0.0.1:4173/ >/dev/null; then
              echo "✅ Preview responded"
              break
            fi
            sleep 1
          done
          echo "--- last 80 lines of preview.log ---"
          tail -n 80 preview.log || true

      - name: Upload preview logs on failure
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: vite-preview-logs
          path: web/frontend/preview.log
          if-no-files-found: ignore

      - name: Upload built site (dist)
        uses: actions/upload-artifact@v4
        with:
          name: frontend-dist
          path: web/frontend/dist/**
          if-no-files-found: error
