name: Host build smoke (Render parity)
on:
  workflow_dispatch: {}
  push:
    branches: [main]
    paths:
      - "web/frontend/**"
permissions: { contents: read }
jobs:
  host-smoke:
    runs-on: ubuntu-latest
    env:
      HUSKY: "0"
      npm_config_ignore_scripts: "true"
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with: { node-version: 20, cache: npm, cache-dependency-path: web/frontend/package-lock.json }
      - name: Install
        run: |
          if [ -f web/frontend/package-lock.json ]; then npm --prefix web/frontend ci; else npm --prefix web/frontend install; fi
      - name: Build (base=/)
        run: npm --prefix web/frontend run build -- --base="/"
      - name: Add SPA 404
        run: cp web/frontend/dist/index.html web/frontend/dist/404.html || true
      - name: Preview & curl
        run: |
          npx --prefix web/frontend vite preview --port 4173 --strictPort --host 127.0.0.1 > /dev/null 2>&1 &
          for i in {1..20}; do curl -fsS http://127.0.0.1:4173/ >/dev/null && break || sleep 0.5; done
          curl -sSI http://127.0.0.1:4173/ | head -n 1
