name: Smoke (Vite build + preview)
on:
  push:
    branches: [ main ]
  workflow_dispatch: {}
jobs:
  smoke:
    runs-on: ubuntu-24.04
    env:
      HUSKY: 0
      NPM_CONFIG_AUDIT: false
      NPM_CONFIG_FUND: false
      npm_config_ignore_scripts: true
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
          cache-dependency-path: web/frontend/package-lock.json
      - name: Install
        run: |
          if [ -f web/frontend/package-lock.json ]; then
            npm --prefix web/frontend ci
          else
            npm --prefix web/frontend install
          fi
      - name: Build (Pages base)
        run: |
          REPO="$(basename "$GITHUB_REPOSITORY")"
          npm --prefix web/frontend run build -- --base="/$REPO/"
          cp web/frontend/dist/index.html web/frontend/dist/404.html || true
      - name: Preview & curl
        run: |
          npx --yes serve -s web/frontend/dist -l 4173 >/dev/null 2>&1 &
          for i in {1..30}; do
            code=$(curl -sso /dev/null -w "%{http_code}" "http://127.0.0.1:4173/") || true
            [ "$code" = "200" ] && break || sleep 0.5
          done
          [ "$code" = "200" ] || (echo "not 200"; exit 1)
