name: Sync Stripe Prices to Render
on:
  workflow_dispatch:
    inputs:
      mode:
        description: "apply or dry-run"
        type: choice
        options: [apply, dry-run]
        default: dry-run
      domain:
        description: "Primary domain (e.g., abando.ai). Leave blank if using service_name."
        required: false
        default: "abando.ai"
      service_name:
        description: "Render service name (used if domain is blank)"
        required: false
        default: ""
  push:
    branches: [ "main" ]
permissions:
  contents: read
jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: sudo apt-get update && sudo apt-get install -y jq
      - run: chmod +x scripts/sync-prices-to-render.sh
      - name: Run sync
        env:
          STRIPE_SECRET_KEY: ${{ secrets.STRIPE_SECRET_KEY }}
          RENDER_API_KEY:    ${{ secrets.RENDER_API_KEY }}
        run: |
          set -euo pipefail
          MODE="${{ inputs.mode || 'dry-run' }}"
          DOMAIN="${{ inputs.domain }}"
          SVCNAME="${{ inputs.service_name }}"
          ARGS=()
          if [ -n "$DOMAIN" ]; then ARGS+=( --domain "$DOMAIN" ); fi
          if [ -n "$SVCNAME" ]; then ARGS+=( --service "$SVCNAME" ); fi
          if [ "$MODE" = "apply" ]; then ARGS+=( --apply ); fi
          echo "scripts/sync-prices-to-render.sh ${ARGS[*]}"
          scripts/sync-prices-to-render.sh "${ARGS[@]}"
