name: Sync Stripe Prices to Render

on:
  workflow_dispatch:
    inputs:
      mode:
        description: "apply or dry-run"
        type: choice
        options: [apply, dry-run]
        default: dry-run
      domain:
        description: "Primary domain (e.g., abando.ai). Leave blank if using service_name."
        required: false
        default: "abando.ai"
      service_name:
        description: "Render service name (used if domain is blank)"
        required: false
        default: ""
  schedule:
    # Nightly dry-run to detect drift early without changing prod
    - cron: "17 6 * * *"

permissions:
  contents: read

concurrency:
  group: sync-prices-to-render-${{ github.ref }}
  cancel-in-progress: true

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install jq
        run: sudo apt-get update && sudo apt-get install -y jq

      - name: Ensure script is executable
        run: chmod +x scripts/sync-prices-to-render.sh

      - name: Show planned target & mode
        run: |
          echo "mode: ${{ inputs.mode || 'dry-run' }}"
          echo "domain: ${{ inputs.domain }}"
          echo "service_name: ${{ inputs.service_name }}"

      - name: Run sync (dry-run by default)
        env:
          STRIPE_SECRET_KEY: ${{ secrets.STRIPE_SECRET_KEY }}
          RENDER_API_KEY:    ${{ secrets.RENDER_API_KEY }}
        run: |
          set -euo pipefail
          MODE="${{ inputs.mode || 'dry-run' }}"
          DOMAIN="${{ inputs.domain }}"
          SVCNAME="${{ inputs.service_name }}"

          ARGS=()
          if [ -n "$DOMAIN" ]; then ARGS+=( --domain "$DOMAIN" ); fi
          if [ -n "$SVCNAME" ]; then ARGS+=( --service "$SVCNAME" ); fi
          if [ "$MODE" = "apply" ]; then ARGS+=( --apply ); fi

          echo "scripts/sync-prices-to-render.sh ${ARGS[*]}"
          scripts/sync-prices-to-render.sh "${ARGS[@]}"
